/**
 * @autogenerated
 * @license Apache-2.0
 */

export enum Currency {
  // Euro
  EUR = 1,
  // United States Dollar
  USD = 2,
  // Bitcoin
  BTC = 3,
  // Ethereum
  ETH = 4,
  // Ethereum Classic
  ETC = 5,
  // Ripple
  XRP = 6,
  // Zcash
  ZEC = 7,
  // Bitcoin Cash
  BCH = 8,
  // Litecoin
  LTC = 9,
  // ArtByte
  ABY = 12,
  // Achain
  ACT = 19,
  // Cardano
  ADA = 20,
  // adToken
  ADT = 26,
  // AdEx
  ADX = 27,
  // Aeternity
  AE = 29,
  // Aeon
  AEON = 30,
  // Agoras Tokens
  AGRS = 32,
  // Aion
  AION = 35,
  // AirToken
  AIR = 36,
  // ALIS
  ALIS = 38,
  // Ambrosus
  AMB = 43,
  // Synereo
  AMP = 47,
  // Aragon
  ANT = 51,
  // Ardor
  ARDR = 59,
  // Ark
  ARK = 63,
  // AirSwap
  AST = 68,
  // ATBCoin
  ATB = 69,
  // ATMCoin
  ATMC = 73,
  // Auroracoin
  AUR = 79,
  // Aventus
  AVT = 82,
  // SegWit2x [Futures]
  B2X = 85,
  // BitBay
  BAY = 90,
  // Basic Attention Token
  BAT = 92,
  // BitConnect
  BCC = 94,
  // Bytecoin
  BCN = 97,
  // BridgeCoin
  BCO = 98,
  // BlockMason Credit Protocol
  BCPT = 99,
  // Bitcrystals
  BCY = 100,
  // Bitdeal
  BDL = 101,
  // Bela
  BELA = 102,
  // Bismuth
  BIS = 112,
  // BitBean
  BITB = 114,
  // bitCNY
  BITCNY = 117,
  // bitUSD
  BITUSD = 123,
  // Blitzcash
  BLITZ = 128,
  // BlackCoin
  BLK = 129,
  // Blocknet
  BLOCK = 131,
  // Blackmoon Crypto
  BMC = 138,
  // Binance Coin
  BNB = 139,
  // Bancor
  BNT = 140,
  // Breakout
  BRK = 154,
  // BitSend
  BSD = 158,
  // BitSoar
  BSR = 160,
  // BT2 [CST]
  BT2 = 164,
  // BitcoinDark
  BTCD = 168,
  // BitShares
  BTS = 176,
  // Bitcoin Unlimited (Futures)
  BTU = 178,
  // Bitcore
  BTX = 180,
  // Burst
  BURST = 185,
  // Bytecent
  BYC = 190,
  // Bitcoin Gold
  BTG = 192,
  // Bytom
  BTM = 194,
  // Change
  CAG = 195,
  // CannabisCoin
  CANN = 198,
  // Crystal Clear 
  CCT = 208,
  // CoinDash
  CDT = 210,
  // Cofound.it
  CFI = 213,
  // ChainCoin
  CHC = 215,
  // Clams
  CLAM = 220,
  // CloakCoin
  CLOAK = 222,
  // ClubCoin
  CLUB = 223,
  // BlockCAT
  CAT = 227,
  // Cindicator
  CND = 229,
  // Cryptonex
  CNX = 233,
  // Cobinhood
  COB = 235,
  // ColossusCoinXT
  COLX = 236,
  // COSS
  COSS = 241,
  // Circuits of Value
  COVAL = 243,
  // Capricoin
  CPC = 245,
  // Creditbit
  CRB = 248,
  // Crown
  CRW = 254,
  // CyberMiles
  CMT = 257,
  // BitDice
  CSNO = 258,
  // Centra
  CTR = 262,
  // Curecoin
  CURE = 264,
  // Colossuscoin V2
  CV2 = 265,
  // Civic
  CVC = 266,
  // Dash
  DASH = 276,
  // Streamr DATAcoin
  DATA = 278,
  // DubaiCoin
  DBIX = 282,
  // Dentacoin
  DCN = 284,
  // Decred
  DCR = 285,
  // DECENT
  DCT = 287,
  // Dent
  DENT = 291,
  // DraftCoin
  DFT = 295,
  // DigiByte
  DGB = 296,
  // DigixDAO
  DGD = 299,
  // Dimecoin
  DIME = 302,
  // Agrello
  DLT = 307,
  // Diamond
  DMD = 310,
  // district0x
  DNT = 312,
  // Dogecoin
  DOGE = 313,
  // DopeCoin
  DOPE = 316,
  // Dotcoin
  DOT = 317,
  // Databits
  DTB = 327,
  // Dynamic
  DYN = 332,
  // eBoost
  EBST = 337,
  // Electra
  ECA = 339,
  // Edgeless
  EDG = 345,
  // Eidoo
  EDO = 346,
  // E-Dinar Coin
  EDR = 348,
  // e-Gulden
  EFL = 350,
  // EverGreenCoin
  EGC = 353,
  // Elixir
  ELIX = 361,
  // Emercoin
  EMC = 366,
  // Einsteinium
  EMC2 = 367,
  // Enigma
  ENG = 371,
  // Enjin Coin
  ENJ = 372,
  // Energycoin
  ENRG = 373,
  // EOS
  EOS = 376,
  // EuropeCoin
  ERC = 379,
  // Espers
  ESP = 382,
  // Ethereum Dark
  ETHD = 385,
  // Electroneum
  ETN = 386,
  // Metaverse ETP
  ETP = 387,
  // Everex
  EVX = 394,
  // ExclusiveCoin
  EXCL = 395,
  // Expanse
  EXP = 398,
  // Factom
  FCT = 407,
  // FoldingCoin
  FLDC = 417,
  // FlorinCoin
  FLO = 419,
  // Fargocoin
  FRGC = 428,
  // FirstCoin
  FRST = 431,
  // Feathercoin
  FTC = 434,
  // Etherparty
  FUEL = 436,
  // FunFair
  FUN = 437,
  // FlypMe
  FYP = 444,
  // Gambit
  GAM = 448,
  // GameCredits
  GAME = 449,
  // Gas
  GAS = 452,
  // Golos Gold
  GBG = 456,
  // Byteball Bytes
  GBYTE = 459,
  // Global Currency Reserve
  GCR = 461,
  // GeoCoin
  GEO = 463,
  // GoldCoin
  GLD = 466,
  // Gnosis
  GNO = 471,
  // Golem
  GNT = 472,
  // Golos
  GOLOS = 474,
  // GridCoin
  GRC = 479,
  // Groestlcoin
  GRS = 483,
  // Matchpool
  GUP = 490,
  // GXShares
  GXS = 491,
  // Hedge
  HDG = 497,
  // Humaniq
  HMQ = 506,
  // Hshare
  HSR = 510,
  // Hush
  HUSH = 514,
  // Hive
  HVN = 516,
  // InvestFeed
  IFT = 532,
  // Incent
  INCNT = 536,
  // Indorse Token
  IND = 537,
  // InfChain
  INF = 539,
  // Influxcoin
  INFX = 540,
  // I/O Coin
  IOC = 544,
  // ION
  ION = 545,
  // Internet of People
  IOP = 546,
  // iXledger
  IXT = 555,
  // KuCoin Shares
  KCS = 568,
  // KickCoin
  KICK = 573,
  // Kin
  KIN = 574,
  // Kolion
  KLN = 576,
  // Komodo
  KMD = 577,
  // Kore
  KORE = 579,
  // LAToken
  LA = 584,
  // LBRY Credits
  LBC = 587,
  // Legends Room
  LGD = 596,
  // Linda
  LINDA = 598,
  // ChainLink
  LINK = 599,
  // Lykke
  LKK = 603,
  // LLToken
  LLT = 604,
  // LoMoCoin
  LMC = 605,
  // Iconomi
  ICN = 608,
  // Loopring
  LRC = 609,
  // Lisk
  LSK = 610,
  // Lunyr
  LUN = 617,
  // LUXCoin
  LUX = 619,
  // MaidSafeCoin
  MAID = 624,
  // Decentraland
  MANA = 625,
  // Marscoin
  MARS = 628,
  // Embers
  MBRS = 635,
  // MCAP
  MCAP = 636,
  // Monaco
  MCO = 638,
  // Moeda Loyalty Points
  MDA = 641,
  // Memetic / PepeCoin
  MEME = 643,
  // Mercury
  MER = 646,
  // MobileGo
  MGO = 650,
  // Mintcoin
  MINT = 653,
  // IOTA
  MIOTA = 654,
  // Melon
  MLN = 656,
  // MinexCoin
  MNX = 661,
  // Modum
  MOD = 662,
  // Moin
  MOIN = 663,
  // MonaCoin
  MONA = 665,
  // Mooncoin
  MOON = 668,
  // Kyber Network
  KNC = 671,
  // Miners' Reward Token
  MRT = 673,
  // Mothership
  MSP = 676,
  // Monetha
  MTH = 678,
  // Metal
  MTL = 679,
  // MonetaryUnit
  MUE = 683,
  // Musicoin
  MUSIC = 685,
  // Mysterium
  MYST = 688,
  // Nebulas
  NAS = 692,
  // NAV Coin
  NAV = 694,
  // Neblio
  NEBL = 699,
  // NEO
  NEO = 700,
  // NeosCoin
  NEOS = 701,
  // NoLimitCoin
  NLC2 = 706,
  // Gulden
  NLG = 707,
  // Namecoin
  NMC = 708,
  // Numeraire
  NMR = 709,
  // Nuls
  NULS = 720,
  // Novacoin
  NVC = 721,
  // Nexium
  NXC = 723,
  // Nexus
  NXS = 724,
  // Nxt
  NXT = 725,
  // OAX
  OAX = 729,
  // OracleChain
  OCT = 734,
  // Obsidian
  ODN = 735,
  // OKCash
  OK = 738,
  // OmiseGO
  OMG = 740,
  // Omni
  OMNI = 741,
  // DeepOnion
  ONION = 742,
  // Ormeus Coin
  ORME = 750,
  // Open Trading Network
  OTN = 752,
  // Paccoin
  PAC = 755,
  // Particl
  PART = 757,
  // Pascal Coin
  PASC = 758,
  // TenX
  PAY = 760,
  // Primalbase Token
  PBT = 762,
  // Project Decorum
  PDC = 765,
  // Peacecoin
  PEC = 767,
  // Pepe Cash
  PEPECASH = 768,
  // PinkCoin
  PINK = 777,
  // Pirl
  PIRL = 779,
  // PIVX
  PIVX = 780,
  // ParkByte
  PKB = 783,
  // Polybius
  PLBT = 785,
  // Pillar
  PLR = 787,
  // Po.et
  POE = 790,
  // ClearPoll
  POLL = 792,
  // PoSW Coin
  POSW = 797,
  // PotCoin
  POT = 798,
  // Power Ledger
  POWR = 799,
  // Peercoin
  PPC = 800,
  // PayPie
  PPP = 801,
  // Populous
  PPT = 802,
  // Nimiq
  NET = 803,
  // Paragon
  PRG = 807,
  // Primas
  PST = 815,
  // Pesetacoin
  PTC = 817,
  // Patientory
  PTOY = 818,
  // Pura
  PURA = 820,
  // Quantum Resistant Ledger
  QRL = 835,
  // Qtum
  QTUM = 837,
  // Qwark
  QWARK = 839,
  // Revain
  R = 840,
  // Radium
  RADS = 841,
  // Rubycoin
  RBY = 847,
  // ReddCoin
  RDD = 849,
  // Regalcoin
  REC = 851,
  // Augur
  REP = 855,
  // Request Network
  REQ = 856,
  // RChain
  RHOC = 860,
  // Riecoin
  RIC = 861,
  // Rise
  RISE = 864,
  // iExec RLC
  RLC = 867,
  // Red Pulse
  RPX = 873,
  // Rivetz
  RVT = 880,
  // SALT
  SALT = 884,
  // Santiment Network Token
  SAN = 885,
  // Steem Dollars
  SBD = 887,
  // Siacoin
  SC = 888,
  // Sequence
  SEQ = 896,
  // Shift
  SHIFT = 903,
  // SIBCoin
  SIB = 906,
  // Skycoin
  SKY = 916,
  // SolarCoin
  SLR = 922,
  // SaluS
  SLS = 923,
  // SunContract
  SNC = 929,
  // SingularDTV
  SNGLS = 931,
  // SONM
  SNM = 932,
  // Synergy
  SNRG = 933,
  // Status
  SNT = 934,
  // Soarcoin
  SOAR = 935,
  // Sphere
  SPHR = 944,
  // Qbao
  QBT = 945,
  // SpreadCoin
  SPR = 946,
  // Startcoin
  START = 951,
  // Steem
  STEEM = 953,
  // Storj
  STORJ = 956,
  // Stratis
  STRAT = 957,
  // Stox
  STX = 961,
  // Substratum
  SUB = 962,
  // Sumokoin
  SUMO = 963,
  // Ripio Credit Network
  RCN = 965,
  // Bitswift
  SWIFT = 966,
  // Swarm City
  SWT = 969,
  // Sexcoin
  SXC = 970,
  // Syndicate
  SYNX = 972,
  // Syscoin
  SYS = 973,
  // TaaS
  TAAS = 974,
  // HempCoin
  THC = 992,
  // TechShares
  THS = 993,
  // Chronobank
  TIME = 994,
  // TokenCard
  TKN = 997,
  // Tokes
  TKS = 999,
  // Tierion
  TNT = 1001,
  // Triggers
  TRIG = 1013,
  // WeTrust
  TRST = 1016,
  // TRON
  TRX = 1019,
  // TransferCoin
  TX = 1024,
  // Ubiq
  UBQ = 1028,
  // UG Token
  UGT = 1031,
  // UnbreakableCoin
  UNB = 1034,
  // Universal Currency
  UNIT = 1039,
  // SmartCash
  SMART = 1049,
  // Tether
  USDT = 1050,
  // NuBits
  USNBT = 1051,
  // Veritaseum
  VERI = 1060,
  // Viacoin
  VIA = 1062,
  // Viberate
  VIB = 1063,
  // VIBE
  VIBE = 1064,
  // Voise
  VOISE = 1071,
  // Voxels
  VOX = 1073,
  // VeriCoin
  VRC = 1076,
  // VeriumReserve
  VRM = 1077,
  // Vertcoin
  VTC = 1082,
  // vTorrent
  VTR = 1083,
  // Waves
  WAVES = 1088,
  // Waves Community Token
  WCT = 1092,
  // Wagerr
  WGR = 1097,
  // WhaleCoin
  WHL = 1098,
  // Wings
  WINGS = 1101,
  // Walton
  WTC = 1108,
  // Giga Watt Token
  WTT = 1109,
  // Asch
  XAS = 1112,
  // Xaurum
  XAUR = 1114,
  // Bitcoin Plus
  XBC = 1115,
  // XTRABYTES
  XBY = 1119,
  // Counterparty
  XCP = 1123,
  // DigitalNote
  XDN = 1129,
  // Elastic
  XEL = 1130,
  // NEM
  XEM = 1131,
  // Infinity Economics
  XIN = 1136,
  // Stellar
  XLM = 1140,
  // Solaris
  XLR = 1141,
  // Monoeci
  XMCC = 1142,
  // Magi
  XMG = 1143,
  // Monero
  XMR = 1144,
  // Myriad
  XMY = 1145,
  // Experience Points
  XP = 1150,
  // Primecoin
  XPM = 1153,
  // RaiBlocks
  XRB = 1158,
  // Rialto
  XRL = 1161,
  // SHIELD
  XSH = 1163,
  // Spectrecoin
  XSPEC = 1164,
  // Stealthcoin
  XST = 1165,
  // Tezos (Pre-Launch)
  XTZ = 1170,
  // Exchange Union
  XUC = 1171,
  // Vcash
  XVC = 1172,
  // Verge
  XVG = 1174,
  // WhiteCoin
  XWC = 1176,
  // ZCoin
  XZC = 1177,
  // YOYOW
  YOYOW = 1182,
  // ZClassic
  ZCL = 1185,
  // ZenCash
  ZEN = 1187,
  // Zero
  ZER = 1190,
  // Bitzeny
  ZNY = 1194,
  // Zoin
  ZOI = 1195,
  // ZrCoin
  ZRC = 1196,
  // 0x
  ZRX = 1197,
  // Zeusshield
  ZSC = 1198,
  // ELTCOIN
  ELTCOIN = 1202,
  // Pure
  PURE = 1204,
  // Desire
  DSR = 1206,
  // Unikoin Gold
  UKG = 1208,
  // POLY AI
  AI = 1211,
  // ALQO
  ALQO = 1212,
  // MicroMoney
  AMM = 1213,
  // Aeron
  ARN = 1214,
  // Bitcoin Diamond
  BCD = 1219,
  // BitcoinX [Futures]
  BCX = 1221,
  // Bibox Token
  BIX = 1222,
  // Bounty0x
  BNTY = 1223,
  // Bodhi
  BOT = 1225,
  // Bread
  BRD = 1227,
  // Bitair
  BTCA = 1229,
  // BitSerial
  BTE = 1230,
  // Bulwark
  BWK = 1231,
  // Cappasity
  CAPP = 1232,
  // CrowdCoin
  CRC = 1235,
  // Verify
  CRED = 1236,
  // Dai
  DAI = 1239,
  // Datum
  DAT = 1240,
  // DavorCoin
  DAV = 1241,
  // DEW
  DEW = 1243,
  // DIMCOIN
  DIM = 1245,
  // Divi
  DIVX = 1246,
  // EncrypGen
  DNA = 1247,
  // Delphy
  DPY = 1248,
  // Dragonchain
  DRGN = 1249,
  // Dynamic Trading Rights
  DTR = 1251,
  // EA Coin
  EAG = 1252,
  // aelf
  ELF = 1256,
  // Ethos
  ETHOS = 1260,
  // Filecoin [Futures]
  FIL = 1263,
  // Flixxo
  FLIXX = 1264,
  // GoByte
  GBX = 1267,
  // Genaro Network
  GNX = 1269,
  // GOLD Reward Token
  GRX = 1271,
  // Gifto
  GTO = 1272,
  // Genesis Vision
  GVT = 1273,
  // Hawala.Today
  HAT = 1274,
  // Decision Token
  HST = 1276,
  // HollyWoodCoin
  HWC = 1277,
  // Ink
  INK = 1280,
  // Innova
  INN = 1281,
  // IoT Chain
  ITC = 1283,
  // IntenseCoin
  ITNS = 1284,
  // ETHLend
  LEND = 1286,
  // Magnet
  MAG = 1288,
  // MagicCoin
  MAGE = 1289,
  // MediShares
  MDS = 1290,
  // Medibloc
  MED = 1291,
  // Maker
  MKR = 1292,
  // Monkey Project
  MONK = 1294,
  // NAGA
  NGC = 1297,
  // Simple Token
  OST = 1300,
  // Publica
  PBL = 1303,
  // Payfair
  PFR = 1305,
  // Phore
  PHR = 1306,
  // Oyster Pearl
  PRL = 1313,
  // QASH
  QASH = 1314,
  // Quantstamp
  QSP = 1315,
  // Raiden Network Token
  RDN = 1316,
  // SagaCoin
  SAGA = 1319,
  // StrikeBitClub
  SBC = 1320,
  // Super Bitcoin
  SBTC = 1321,
  // SmartMesh
  SMT = 1326,
  // Snovio
  SNOV = 1327,
  // SpankChain
  SPANK = 1328,
  // SportyFi
  SPF = 1329,
  // SophiaTX
  SPHTX = 1330,
  // SIRIN LABS Token
  SRN = 1331,
  // Santa Coin
  STC = 1335,
  // Storm
  STORM = 1336,
  // Blocktix
  TIX = 1339,
  // Time New Bank
  TNB = 1340,
  // Energo
  TSL = 1344,
  // Sphre AIR 
  XID = 1345,
  // United Bitcoin
  UBTC = 1346,
  // Uquid Coin
  UQC = 1348,
  // BLOCKv
  VEE = 1349,
  // VeChain
  VET = 1350,
  // Viuly
  VIU = 1351,
  // WaBi
  WABI = 1353,
  // WAX
  WAX = 1354,
  // WINCOIN
  WC = 1355,
  // MyWish
  WISH = 1356,
  // Worldcore
  WRC = 1357,
  // Copico
  XCPO = 1358,
}
