// Currency symbols utilities.
// SEE: tools/update-coins/symbols.rs.tmpl
// @autogenerated

use std::convert::TryFrom;

use super::errors::{Error, ErrorKind};

/// Currency symbol.
#[derive(Serialize, Deserialize, PartialEq, Clone)]
pub enum Symbol {
    /// Euro
    EUR = 1,
    /// United States Dollar
    USD = 2,
    /// Bitcoin
    BTC = 3,
    /// Ethereum
    ETH = 4,
    /// Ethereum Classic
    ETC = 5,
    /// Ripple
    XRP = 6,
    /// Zcash
    ZEC = 7,
    /// Bitcoin Cash
    BCH = 8,
    /// Litecoin
    LTC = 9,
    /// ArtByte
    ABY = 12,
    /// Achain
    ACT = 19,
    /// Cardano
    ADA = 20,
    /// adToken
    ADT = 26,
    /// AdEx
    ADX = 27,
    /// Aeternity
    AE = 29,
    /// Aeon
    AEON = 30,
    /// Agoras Tokens
    AGRS = 32,
    /// Aion
    AION = 35,
    /// AirToken
    AIR = 36,
    /// ALIS
    ALIS = 38,
    /// Ambrosus
    AMB = 43,
    /// Synereo
    AMP = 47,
    /// Aragon
    ANT = 51,
    /// Ardor
    ARDR = 59,
    /// Ark
    ARK = 63,
    /// AirSwap
    AST = 68,
    /// ATBCoin
    ATB = 69,
    /// ATMCoin
    ATMC = 73,
    /// Auroracoin
    AUR = 79,
    /// Aventus
    AVT = 82,
    /// SegWit2x [Futures]
    B2X = 85,
    /// BitBay
    BAY = 90,
    /// Basic Attention Token
    BAT = 92,
    /// BitConnect
    BCC = 94,
    /// Bytecoin
    BCN = 97,
    /// BridgeCoin
    BCO = 98,
    /// BlockMason Credit Protocol
    BCPT = 99,
    /// Bitcrystals
    BCY = 100,
    /// Bitdeal
    BDL = 101,
    /// Bela
    BELA = 102,
    /// Bismuth
    BIS = 112,
    /// BitBean
    BITB = 114,
    /// bitCNY
    BITCNY = 117,
    /// bitUSD
    BITUSD = 123,
    /// Blitzcash
    BLITZ = 128,
    /// BlackCoin
    BLK = 129,
    /// Blocknet
    BLOCK = 131,
    /// Blackmoon Crypto
    BMC = 138,
    /// Binance Coin
    BNB = 139,
    /// Bancor
    BNT = 140,
    /// Breakout
    BRK = 154,
    /// BitSend
    BSD = 158,
    /// BitSoar
    BSR = 160,
    /// BT2 [CST]
    BT2 = 164,
    /// BitcoinDark
    BTCD = 168,
    /// BitShares
    BTS = 176,
    /// Bitcoin Unlimited (Futures)
    BTU = 178,
    /// Bitcore
    BTX = 180,
    /// Burst
    BURST = 185,
    /// Bytecent
    BYC = 190,
    /// Bitcoin Gold
    BTG = 192,
    /// Bytom
    BTM = 194,
    /// Change
    CAG = 195,
    /// CannabisCoin
    CANN = 198,
    /// Crystal Clear 
    CCT = 208,
    /// CoinDash
    CDT = 210,
    /// Cofound.it
    CFI = 213,
    /// ChainCoin
    CHC = 215,
    /// Clams
    CLAM = 220,
    /// CloakCoin
    CLOAK = 222,
    /// ClubCoin
    CLUB = 223,
    /// BlockCAT
    CAT = 227,
    /// Cindicator
    CND = 229,
    /// Cryptonex
    CNX = 233,
    /// Cobinhood
    COB = 235,
    /// ColossusCoinXT
    COLX = 236,
    /// COSS
    COSS = 241,
    /// Circuits of Value
    COVAL = 243,
    /// Capricoin
    CPC = 245,
    /// Creditbit
    CRB = 248,
    /// Crown
    CRW = 254,
    /// CyberMiles
    CMT = 257,
    /// BitDice
    CSNO = 258,
    /// Centra
    CTR = 262,
    /// Curecoin
    CURE = 264,
    /// Colossuscoin V2
    CV2 = 265,
    /// Civic
    CVC = 266,
    /// Dash
    DASH = 276,
    /// Streamr DATAcoin
    DATA = 278,
    /// DubaiCoin
    DBIX = 282,
    /// Dentacoin
    DCN = 284,
    /// Decred
    DCR = 285,
    /// DECENT
    DCT = 287,
    /// Dent
    DENT = 291,
    /// DraftCoin
    DFT = 295,
    /// DigiByte
    DGB = 296,
    /// DigixDAO
    DGD = 299,
    /// Dimecoin
    DIME = 302,
    /// Agrello
    DLT = 307,
    /// Diamond
    DMD = 310,
    /// district0x
    DNT = 312,
    /// Dogecoin
    DOGE = 313,
    /// DopeCoin
    DOPE = 316,
    /// Dotcoin
    DOT = 317,
    /// Databits
    DTB = 327,
    /// Dynamic
    DYN = 332,
    /// eBoost
    EBST = 337,
    /// Electra
    ECA = 339,
    /// Edgeless
    EDG = 345,
    /// Eidoo
    EDO = 346,
    /// E-Dinar Coin
    EDR = 348,
    /// e-Gulden
    EFL = 350,
    /// EverGreenCoin
    EGC = 353,
    /// Elixir
    ELIX = 361,
    /// Emercoin
    EMC = 366,
    /// Einsteinium
    EMC2 = 367,
    /// Enigma
    ENG = 371,
    /// Enjin Coin
    ENJ = 372,
    /// Energycoin
    ENRG = 373,
    /// EOS
    EOS = 376,
    /// EuropeCoin
    ERC = 379,
    /// Espers
    ESP = 382,
    /// Ethereum Dark
    ETHD = 385,
    /// Electroneum
    ETN = 386,
    /// Metaverse ETP
    ETP = 387,
    /// Everex
    EVX = 394,
    /// ExclusiveCoin
    EXCL = 395,
    /// Expanse
    EXP = 398,
    /// Factom
    FCT = 407,
    /// FoldingCoin
    FLDC = 417,
    /// FlorinCoin
    FLO = 419,
    /// Fargocoin
    FRGC = 428,
    /// FirstCoin
    FRST = 431,
    /// Feathercoin
    FTC = 434,
    /// Etherparty
    FUEL = 436,
    /// FunFair
    FUN = 437,
    /// FlypMe
    FYP = 444,
    /// Gambit
    GAM = 448,
    /// GameCredits
    GAME = 449,
    /// Gas
    GAS = 452,
    /// Golos Gold
    GBG = 456,
    /// Byteball Bytes
    GBYTE = 459,
    /// Global Currency Reserve
    GCR = 461,
    /// GeoCoin
    GEO = 463,
    /// GoldCoin
    GLD = 466,
    /// Gnosis
    GNO = 471,
    /// Golem
    GNT = 472,
    /// Golos
    GOLOS = 474,
    /// GridCoin
    GRC = 479,
    /// Groestlcoin
    GRS = 483,
    /// Matchpool
    GUP = 490,
    /// GXShares
    GXS = 491,
    /// Hedge
    HDG = 497,
    /// Humaniq
    HMQ = 506,
    /// Hshare
    HSR = 510,
    /// Hush
    HUSH = 514,
    /// Hive
    HVN = 516,
    /// InvestFeed
    IFT = 532,
    /// Incent
    INCNT = 536,
    /// Indorse Token
    IND = 537,
    /// InfChain
    INF = 539,
    /// Influxcoin
    INFX = 540,
    /// I/O Coin
    IOC = 544,
    /// ION
    ION = 545,
    /// Internet of People
    IOP = 546,
    /// iXledger
    IXT = 555,
    /// KuCoin Shares
    KCS = 568,
    /// KickCoin
    KICK = 573,
    /// Kin
    KIN = 574,
    /// Kolion
    KLN = 576,
    /// Komodo
    KMD = 577,
    /// Kore
    KORE = 579,
    /// LAToken
    LA = 584,
    /// LBRY Credits
    LBC = 587,
    /// Legends Room
    LGD = 596,
    /// Linda
    LINDA = 598,
    /// ChainLink
    LINK = 599,
    /// Lykke
    LKK = 603,
    /// LLToken
    LLT = 604,
    /// LoMoCoin
    LMC = 605,
    /// Iconomi
    ICN = 608,
    /// Loopring
    LRC = 609,
    /// Lisk
    LSK = 610,
    /// Lunyr
    LUN = 617,
    /// LUXCoin
    LUX = 619,
    /// MaidSafeCoin
    MAID = 624,
    /// Decentraland
    MANA = 625,
    /// Marscoin
    MARS = 628,
    /// Embers
    MBRS = 635,
    /// MCAP
    MCAP = 636,
    /// Monaco
    MCO = 638,
    /// Moeda Loyalty Points
    MDA = 641,
    /// Memetic / PepeCoin
    MEME = 643,
    /// Mercury
    MER = 646,
    /// MobileGo
    MGO = 650,
    /// Mintcoin
    MINT = 653,
    /// IOTA
    MIOTA = 654,
    /// Melon
    MLN = 656,
    /// MinexCoin
    MNX = 661,
    /// Modum
    MOD = 662,
    /// Moin
    MOIN = 663,
    /// MonaCoin
    MONA = 665,
    /// Mooncoin
    MOON = 668,
    /// Kyber Network
    KNC = 671,
    /// Miners' Reward Token
    MRT = 673,
    /// Mothership
    MSP = 676,
    /// Monetha
    MTH = 678,
    /// Metal
    MTL = 679,
    /// MonetaryUnit
    MUE = 683,
    /// Musicoin
    MUSIC = 685,
    /// Mysterium
    MYST = 688,
    /// Nebulas
    NAS = 692,
    /// NAV Coin
    NAV = 694,
    /// Neblio
    NEBL = 699,
    /// NEO
    NEO = 700,
    /// NeosCoin
    NEOS = 701,
    /// NoLimitCoin
    NLC2 = 706,
    /// Gulden
    NLG = 707,
    /// Namecoin
    NMC = 708,
    /// Numeraire
    NMR = 709,
    /// Nuls
    NULS = 720,
    /// Novacoin
    NVC = 721,
    /// Nexium
    NXC = 723,
    /// Nexus
    NXS = 724,
    /// Nxt
    NXT = 725,
    /// OAX
    OAX = 729,
    /// OracleChain
    OCT = 734,
    /// Obsidian
    ODN = 735,
    /// OKCash
    OK = 738,
    /// OmiseGO
    OMG = 740,
    /// Omni
    OMNI = 741,
    /// DeepOnion
    ONION = 742,
    /// Ormeus Coin
    ORME = 750,
    /// Open Trading Network
    OTN = 752,
    /// Paccoin
    PAC = 755,
    /// Particl
    PART = 757,
    /// Pascal Coin
    PASC = 758,
    /// TenX
    PAY = 760,
    /// Primalbase Token
    PBT = 762,
    /// Project Decorum
    PDC = 765,
    /// Peacecoin
    PEC = 767,
    /// Pepe Cash
    PEPECASH = 768,
    /// PinkCoin
    PINK = 777,
    /// Pirl
    PIRL = 779,
    /// PIVX
    PIVX = 780,
    /// ParkByte
    PKB = 783,
    /// Polybius
    PLBT = 785,
    /// Pillar
    PLR = 787,
    /// Po.et
    POE = 790,
    /// ClearPoll
    POLL = 792,
    /// PoSW Coin
    POSW = 797,
    /// PotCoin
    POT = 798,
    /// Power Ledger
    POWR = 799,
    /// Peercoin
    PPC = 800,
    /// PayPie
    PPP = 801,
    /// Populous
    PPT = 802,
    /// Nimiq
    NET = 803,
    /// Paragon
    PRG = 807,
    /// Primas
    PST = 815,
    /// Pesetacoin
    PTC = 817,
    /// Patientory
    PTOY = 818,
    /// Pura
    PURA = 820,
    /// Quantum Resistant Ledger
    QRL = 835,
    /// Qtum
    QTUM = 837,
    /// Qwark
    QWARK = 839,
    /// Revain
    R = 840,
    /// Radium
    RADS = 841,
    /// Rubycoin
    RBY = 847,
    /// ReddCoin
    RDD = 849,
    /// Regalcoin
    REC = 851,
    /// Augur
    REP = 855,
    /// Request Network
    REQ = 856,
    /// RChain
    RHOC = 860,
    /// Riecoin
    RIC = 861,
    /// Rise
    RISE = 864,
    /// iExec RLC
    RLC = 867,
    /// Red Pulse
    RPX = 873,
    /// Rivetz
    RVT = 880,
    /// SALT
    SALT = 884,
    /// Santiment Network Token
    SAN = 885,
    /// Steem Dollars
    SBD = 887,
    /// Siacoin
    SC = 888,
    /// Sequence
    SEQ = 896,
    /// Shift
    SHIFT = 903,
    /// SIBCoin
    SIB = 906,
    /// Skycoin
    SKY = 916,
    /// SolarCoin
    SLR = 922,
    /// SaluS
    SLS = 923,
    /// SunContract
    SNC = 929,
    /// SingularDTV
    SNGLS = 931,
    /// SONM
    SNM = 932,
    /// Synergy
    SNRG = 933,
    /// Status
    SNT = 934,
    /// Soarcoin
    SOAR = 935,
    /// Sphere
    SPHR = 944,
    /// Qbao
    QBT = 945,
    /// SpreadCoin
    SPR = 946,
    /// Startcoin
    START = 951,
    /// Steem
    STEEM = 953,
    /// Storj
    STORJ = 956,
    /// Stratis
    STRAT = 957,
    /// Stox
    STX = 961,
    /// Substratum
    SUB = 962,
    /// Sumokoin
    SUMO = 963,
    /// Ripio Credit Network
    RCN = 965,
    /// Bitswift
    SWIFT = 966,
    /// Swarm City
    SWT = 969,
    /// Sexcoin
    SXC = 970,
    /// Syndicate
    SYNX = 972,
    /// Syscoin
    SYS = 973,
    /// TaaS
    TAAS = 974,
    /// HempCoin
    THC = 992,
    /// TechShares
    THS = 993,
    /// Chronobank
    TIME = 994,
    /// TokenCard
    TKN = 997,
    /// Tokes
    TKS = 999,
    /// Tierion
    TNT = 1001,
    /// Triggers
    TRIG = 1013,
    /// WeTrust
    TRST = 1016,
    /// TRON
    TRX = 1019,
    /// TransferCoin
    TX = 1024,
    /// Ubiq
    UBQ = 1028,
    /// UG Token
    UGT = 1031,
    /// UnbreakableCoin
    UNB = 1034,
    /// Universal Currency
    UNIT = 1039,
    /// SmartCash
    SMART = 1049,
    /// Tether
    USDT = 1050,
    /// NuBits
    USNBT = 1051,
    /// Veritaseum
    VERI = 1060,
    /// Viacoin
    VIA = 1062,
    /// Viberate
    VIB = 1063,
    /// VIBE
    VIBE = 1064,
    /// Voise
    VOISE = 1071,
    /// Voxels
    VOX = 1073,
    /// VeriCoin
    VRC = 1076,
    /// VeriumReserve
    VRM = 1077,
    /// Vertcoin
    VTC = 1082,
    /// vTorrent
    VTR = 1083,
    /// Waves
    WAVES = 1088,
    /// Waves Community Token
    WCT = 1092,
    /// Wagerr
    WGR = 1097,
    /// WhaleCoin
    WHL = 1098,
    /// Wings
    WINGS = 1101,
    /// Walton
    WTC = 1108,
    /// Giga Watt Token
    WTT = 1109,
    /// Asch
    XAS = 1112,
    /// Xaurum
    XAUR = 1114,
    /// Bitcoin Plus
    XBC = 1115,
    /// XTRABYTES
    XBY = 1119,
    /// Counterparty
    XCP = 1123,
    /// DigitalNote
    XDN = 1129,
    /// Elastic
    XEL = 1130,
    /// NEM
    XEM = 1131,
    /// Infinity Economics
    XIN = 1136,
    /// Stellar
    XLM = 1140,
    /// Solaris
    XLR = 1141,
    /// Monoeci
    XMCC = 1142,
    /// Magi
    XMG = 1143,
    /// Monero
    XMR = 1144,
    /// Myriad
    XMY = 1145,
    /// Experience Points
    XP = 1150,
    /// Primecoin
    XPM = 1153,
    /// RaiBlocks
    XRB = 1158,
    /// Rialto
    XRL = 1161,
    /// SHIELD
    XSH = 1163,
    /// Spectrecoin
    XSPEC = 1164,
    /// Stealthcoin
    XST = 1165,
    /// Tezos (Pre-Launch)
    XTZ = 1170,
    /// Exchange Union
    XUC = 1171,
    /// Vcash
    XVC = 1172,
    /// Verge
    XVG = 1174,
    /// WhiteCoin
    XWC = 1176,
    /// ZCoin
    XZC = 1177,
    /// YOYOW
    YOYOW = 1182,
    /// ZClassic
    ZCL = 1185,
    /// ZenCash
    ZEN = 1187,
    /// Zero
    ZER = 1190,
    /// Bitzeny
    ZNY = 1194,
    /// Zoin
    ZOI = 1195,
    /// ZrCoin
    ZRC = 1196,
    /// 0x
    ZRX = 1197,
    /// Zeusshield
    ZSC = 1198,
    /// ELTCOIN
    ELTCOIN = 1202,
    /// Pure
    PURE = 1204,
    /// Desire
    DSR = 1206,
    /// Unikoin Gold
    UKG = 1208,
    /// POLY AI
    AI = 1211,
    /// ALQO
    ALQO = 1212,
    /// MicroMoney
    AMM = 1213,
    /// Aeron
    ARN = 1214,
    /// Bitcoin Diamond
    BCD = 1219,
    /// BitcoinX [Futures]
    BCX = 1221,
    /// Bibox Token
    BIX = 1222,
    /// Bounty0x
    BNTY = 1223,
    /// Bodhi
    BOT = 1225,
    /// Bread
    BRD = 1227,
    /// Bitair
    BTCA = 1229,
    /// BitSerial
    BTE = 1230,
    /// Bulwark
    BWK = 1231,
    /// Cappasity
    CAPP = 1232,
    /// CrowdCoin
    CRC = 1235,
    /// Verify
    CRED = 1236,
    /// Dai
    DAI = 1239,
    /// Datum
    DAT = 1240,
    /// DavorCoin
    DAV = 1241,
    /// DEW
    DEW = 1243,
    /// DIMCOIN
    DIM = 1245,
    /// Divi
    DIVX = 1246,
    /// EncrypGen
    DNA = 1247,
    /// Delphy
    DPY = 1248,
    /// Dragonchain
    DRGN = 1249,
    /// Dynamic Trading Rights
    DTR = 1251,
    /// EA Coin
    EAG = 1252,
    /// aelf
    ELF = 1256,
    /// Ethos
    ETHOS = 1260,
    /// Filecoin [Futures]
    FIL = 1263,
    /// Flixxo
    FLIXX = 1264,
    /// GoByte
    GBX = 1267,
    /// Genaro Network
    GNX = 1269,
    /// GOLD Reward Token
    GRX = 1271,
    /// Gifto
    GTO = 1272,
    /// Genesis Vision
    GVT = 1273,
    /// Hawala.Today
    HAT = 1274,
    /// Decision Token
    HST = 1276,
    /// HollyWoodCoin
    HWC = 1277,
    /// Ink
    INK = 1280,
    /// Innova
    INN = 1281,
    /// IoT Chain
    ITC = 1283,
    /// IntenseCoin
    ITNS = 1284,
    /// ETHLend
    LEND = 1286,
    /// Magnet
    MAG = 1288,
    /// MagicCoin
    MAGE = 1289,
    /// MediShares
    MDS = 1290,
    /// Medibloc
    MED = 1291,
    /// Maker
    MKR = 1292,
    /// Monkey Project
    MONK = 1294,
    /// NAGA
    NGC = 1297,
    /// Simple Token
    OST = 1300,
    /// Publica
    PBL = 1303,
    /// Payfair
    PFR = 1305,
    /// Phore
    PHR = 1306,
    /// Oyster Pearl
    PRL = 1313,
    /// QASH
    QASH = 1314,
    /// Quantstamp
    QSP = 1315,
    /// Raiden Network Token
    RDN = 1316,
    /// SagaCoin
    SAGA = 1319,
    /// StrikeBitClub
    SBC = 1320,
    /// Super Bitcoin
    SBTC = 1321,
    /// SmartMesh
    SMT = 1326,
    /// Snovio
    SNOV = 1327,
    /// SpankChain
    SPANK = 1328,
    /// SportyFi
    SPF = 1329,
    /// SophiaTX
    SPHTX = 1330,
    /// SIRIN LABS Token
    SRN = 1331,
    /// Santa Coin
    STC = 1335,
    /// Storm
    STORM = 1336,
    /// Blocktix
    TIX = 1339,
    /// Time New Bank
    TNB = 1340,
    /// Energo
    TSL = 1344,
    /// Sphre AIR 
    XID = 1345,
    /// United Bitcoin
    UBTC = 1346,
    /// Uquid Coin
    UQC = 1348,
    /// BLOCKv
    VEE = 1349,
    /// VeChain
    VET = 1350,
    /// Viuly
    VIU = 1351,
    /// WaBi
    WABI = 1353,
    /// WAX
    WAX = 1354,
    /// WINCOIN
    WC = 1355,
    /// MyWish
    WISH = 1356,
    /// Worldcore
    WRC = 1357,
    /// Copico
    XCPO = 1358,
}

/// Tries to convert string to a currency `Symbol`.
impl<'a> TryFrom<&'a str> for Symbol {
    type Error = Error;

    fn try_from(name: &str) -> Result<Self, Self::Error> {
        match name {
            "EUR" => Ok(Symbol::EUR),
            "USD" => Ok(Symbol::USD),
            "BTC" => Ok(Symbol::BTC),
            "ETH" => Ok(Symbol::ETH),
            "ETC" => Ok(Symbol::ETC),
            "XRP" => Ok(Symbol::XRP),
            "ZEC" => Ok(Symbol::ZEC),
            "BCH" => Ok(Symbol::BCH),
            "LTC" => Ok(Symbol::LTC),
            "ABY" => Ok(Symbol::ABY),
            "ACT" => Ok(Symbol::ACT),
            "ADA" => Ok(Symbol::ADA),
            "ADT" => Ok(Symbol::ADT),
            "ADX" => Ok(Symbol::ADX),
            "AE" => Ok(Symbol::AE),
            "AEON" => Ok(Symbol::AEON),
            "AGRS" => Ok(Symbol::AGRS),
            "AION" => Ok(Symbol::AION),
            "AIR" => Ok(Symbol::AIR),
            "ALIS" => Ok(Symbol::ALIS),
            "AMB" => Ok(Symbol::AMB),
            "AMP" => Ok(Symbol::AMP),
            "ANT" => Ok(Symbol::ANT),
            "ARDR" => Ok(Symbol::ARDR),
            "ARK" => Ok(Symbol::ARK),
            "AST" => Ok(Symbol::AST),
            "ATB" => Ok(Symbol::ATB),
            "ATMC" => Ok(Symbol::ATMC),
            "AUR" => Ok(Symbol::AUR),
            "AVT" => Ok(Symbol::AVT),
            "B2X" => Ok(Symbol::B2X),
            "BAY" => Ok(Symbol::BAY),
            "BAT" => Ok(Symbol::BAT),
            "BCC" => Ok(Symbol::BCC),
            "BCN" => Ok(Symbol::BCN),
            "BCO" => Ok(Symbol::BCO),
            "BCPT" => Ok(Symbol::BCPT),
            "BCY" => Ok(Symbol::BCY),
            "BDL" => Ok(Symbol::BDL),
            "BELA" => Ok(Symbol::BELA),
            "BIS" => Ok(Symbol::BIS),
            "BITB" => Ok(Symbol::BITB),
            "BITCNY" => Ok(Symbol::BITCNY),
            "BITUSD" => Ok(Symbol::BITUSD),
            "BLITZ" => Ok(Symbol::BLITZ),
            "BLK" => Ok(Symbol::BLK),
            "BLOCK" => Ok(Symbol::BLOCK),
            "BMC" => Ok(Symbol::BMC),
            "BNB" => Ok(Symbol::BNB),
            "BNT" => Ok(Symbol::BNT),
            "BRK" => Ok(Symbol::BRK),
            "BSD" => Ok(Symbol::BSD),
            "BSR" => Ok(Symbol::BSR),
            "BT2" => Ok(Symbol::BT2),
            "BTCD" => Ok(Symbol::BTCD),
            "BTS" => Ok(Symbol::BTS),
            "BTU" => Ok(Symbol::BTU),
            "BTX" => Ok(Symbol::BTX),
            "BURST" => Ok(Symbol::BURST),
            "BYC" => Ok(Symbol::BYC),
            "BTG" => Ok(Symbol::BTG),
            "BTM" => Ok(Symbol::BTM),
            "CAG" => Ok(Symbol::CAG),
            "CANN" => Ok(Symbol::CANN),
            "CCT" => Ok(Symbol::CCT),
            "CDT" => Ok(Symbol::CDT),
            "CFI" => Ok(Symbol::CFI),
            "CHC" => Ok(Symbol::CHC),
            "CLAM" => Ok(Symbol::CLAM),
            "CLOAK" => Ok(Symbol::CLOAK),
            "CLUB" => Ok(Symbol::CLUB),
            "CAT" => Ok(Symbol::CAT),
            "CND" => Ok(Symbol::CND),
            "CNX" => Ok(Symbol::CNX),
            "COB" => Ok(Symbol::COB),
            "COLX" => Ok(Symbol::COLX),
            "COSS" => Ok(Symbol::COSS),
            "COVAL" => Ok(Symbol::COVAL),
            "CPC" => Ok(Symbol::CPC),
            "CRB" => Ok(Symbol::CRB),
            "CRW" => Ok(Symbol::CRW),
            "CMT" => Ok(Symbol::CMT),
            "CSNO" => Ok(Symbol::CSNO),
            "CTR" => Ok(Symbol::CTR),
            "CURE" => Ok(Symbol::CURE),
            "CV2" => Ok(Symbol::CV2),
            "CVC" => Ok(Symbol::CVC),
            "DASH" => Ok(Symbol::DASH),
            "DATA" => Ok(Symbol::DATA),
            "DBIX" => Ok(Symbol::DBIX),
            "DCN" => Ok(Symbol::DCN),
            "DCR" => Ok(Symbol::DCR),
            "DCT" => Ok(Symbol::DCT),
            "DENT" => Ok(Symbol::DENT),
            "DFT" => Ok(Symbol::DFT),
            "DGB" => Ok(Symbol::DGB),
            "DGD" => Ok(Symbol::DGD),
            "DIME" => Ok(Symbol::DIME),
            "DLT" => Ok(Symbol::DLT),
            "DMD" => Ok(Symbol::DMD),
            "DNT" => Ok(Symbol::DNT),
            "DOGE" => Ok(Symbol::DOGE),
            "DOPE" => Ok(Symbol::DOPE),
            "DOT" => Ok(Symbol::DOT),
            "DTB" => Ok(Symbol::DTB),
            "DYN" => Ok(Symbol::DYN),
            "EBST" => Ok(Symbol::EBST),
            "ECA" => Ok(Symbol::ECA),
            "EDG" => Ok(Symbol::EDG),
            "EDO" => Ok(Symbol::EDO),
            "EDR" => Ok(Symbol::EDR),
            "EFL" => Ok(Symbol::EFL),
            "EGC" => Ok(Symbol::EGC),
            "ELIX" => Ok(Symbol::ELIX),
            "EMC" => Ok(Symbol::EMC),
            "EMC2" => Ok(Symbol::EMC2),
            "ENG" => Ok(Symbol::ENG),
            "ENJ" => Ok(Symbol::ENJ),
            "ENRG" => Ok(Symbol::ENRG),
            "EOS" => Ok(Symbol::EOS),
            "ERC" => Ok(Symbol::ERC),
            "ESP" => Ok(Symbol::ESP),
            "ETHD" => Ok(Symbol::ETHD),
            "ETN" => Ok(Symbol::ETN),
            "ETP" => Ok(Symbol::ETP),
            "EVX" => Ok(Symbol::EVX),
            "EXCL" => Ok(Symbol::EXCL),
            "EXP" => Ok(Symbol::EXP),
            "FCT" => Ok(Symbol::FCT),
            "FLDC" => Ok(Symbol::FLDC),
            "FLO" => Ok(Symbol::FLO),
            "FRGC" => Ok(Symbol::FRGC),
            "FRST" => Ok(Symbol::FRST),
            "FTC" => Ok(Symbol::FTC),
            "FUEL" => Ok(Symbol::FUEL),
            "FUN" => Ok(Symbol::FUN),
            "FYP" => Ok(Symbol::FYP),
            "GAM" => Ok(Symbol::GAM),
            "GAME" => Ok(Symbol::GAME),
            "GAS" => Ok(Symbol::GAS),
            "GBG" => Ok(Symbol::GBG),
            "GBYTE" => Ok(Symbol::GBYTE),
            "GCR" => Ok(Symbol::GCR),
            "GEO" => Ok(Symbol::GEO),
            "GLD" => Ok(Symbol::GLD),
            "GNO" => Ok(Symbol::GNO),
            "GNT" => Ok(Symbol::GNT),
            "GOLOS" => Ok(Symbol::GOLOS),
            "GRC" => Ok(Symbol::GRC),
            "GRS" => Ok(Symbol::GRS),
            "GUP" => Ok(Symbol::GUP),
            "GXS" => Ok(Symbol::GXS),
            "HDG" => Ok(Symbol::HDG),
            "HMQ" => Ok(Symbol::HMQ),
            "HSR" => Ok(Symbol::HSR),
            "HUSH" => Ok(Symbol::HUSH),
            "HVN" => Ok(Symbol::HVN),
            "IFT" => Ok(Symbol::IFT),
            "INCNT" => Ok(Symbol::INCNT),
            "IND" => Ok(Symbol::IND),
            "INF" => Ok(Symbol::INF),
            "INFX" => Ok(Symbol::INFX),
            "IOC" => Ok(Symbol::IOC),
            "ION" => Ok(Symbol::ION),
            "IOP" => Ok(Symbol::IOP),
            "IXT" => Ok(Symbol::IXT),
            "KCS" => Ok(Symbol::KCS),
            "KICK" => Ok(Symbol::KICK),
            "KIN" => Ok(Symbol::KIN),
            "KLN" => Ok(Symbol::KLN),
            "KMD" => Ok(Symbol::KMD),
            "KORE" => Ok(Symbol::KORE),
            "LA" => Ok(Symbol::LA),
            "LBC" => Ok(Symbol::LBC),
            "LGD" => Ok(Symbol::LGD),
            "LINDA" => Ok(Symbol::LINDA),
            "LINK" => Ok(Symbol::LINK),
            "LKK" => Ok(Symbol::LKK),
            "LLT" => Ok(Symbol::LLT),
            "LMC" => Ok(Symbol::LMC),
            "ICN" => Ok(Symbol::ICN),
            "LRC" => Ok(Symbol::LRC),
            "LSK" => Ok(Symbol::LSK),
            "LUN" => Ok(Symbol::LUN),
            "LUX" => Ok(Symbol::LUX),
            "MAID" => Ok(Symbol::MAID),
            "MANA" => Ok(Symbol::MANA),
            "MARS" => Ok(Symbol::MARS),
            "MBRS" => Ok(Symbol::MBRS),
            "MCAP" => Ok(Symbol::MCAP),
            "MCO" => Ok(Symbol::MCO),
            "MDA" => Ok(Symbol::MDA),
            "MEME" => Ok(Symbol::MEME),
            "MER" => Ok(Symbol::MER),
            "MGO" => Ok(Symbol::MGO),
            "MINT" => Ok(Symbol::MINT),
            "MIOTA" => Ok(Symbol::MIOTA),
            "MLN" => Ok(Symbol::MLN),
            "MNX" => Ok(Symbol::MNX),
            "MOD" => Ok(Symbol::MOD),
            "MOIN" => Ok(Symbol::MOIN),
            "MONA" => Ok(Symbol::MONA),
            "MOON" => Ok(Symbol::MOON),
            "KNC" => Ok(Symbol::KNC),
            "MRT" => Ok(Symbol::MRT),
            "MSP" => Ok(Symbol::MSP),
            "MTH" => Ok(Symbol::MTH),
            "MTL" => Ok(Symbol::MTL),
            "MUE" => Ok(Symbol::MUE),
            "MUSIC" => Ok(Symbol::MUSIC),
            "MYST" => Ok(Symbol::MYST),
            "NAS" => Ok(Symbol::NAS),
            "NAV" => Ok(Symbol::NAV),
            "NEBL" => Ok(Symbol::NEBL),
            "NEO" => Ok(Symbol::NEO),
            "NEOS" => Ok(Symbol::NEOS),
            "NLC2" => Ok(Symbol::NLC2),
            "NLG" => Ok(Symbol::NLG),
            "NMC" => Ok(Symbol::NMC),
            "NMR" => Ok(Symbol::NMR),
            "NULS" => Ok(Symbol::NULS),
            "NVC" => Ok(Symbol::NVC),
            "NXC" => Ok(Symbol::NXC),
            "NXS" => Ok(Symbol::NXS),
            "NXT" => Ok(Symbol::NXT),
            "OAX" => Ok(Symbol::OAX),
            "OCT" => Ok(Symbol::OCT),
            "ODN" => Ok(Symbol::ODN),
            "OK" => Ok(Symbol::OK),
            "OMG" => Ok(Symbol::OMG),
            "OMNI" => Ok(Symbol::OMNI),
            "ONION" => Ok(Symbol::ONION),
            "ORME" => Ok(Symbol::ORME),
            "OTN" => Ok(Symbol::OTN),
            "PAC" => Ok(Symbol::PAC),
            "PART" => Ok(Symbol::PART),
            "PASC" => Ok(Symbol::PASC),
            "PAY" => Ok(Symbol::PAY),
            "PBT" => Ok(Symbol::PBT),
            "PDC" => Ok(Symbol::PDC),
            "PEC" => Ok(Symbol::PEC),
            "PEPECASH" => Ok(Symbol::PEPECASH),
            "PINK" => Ok(Symbol::PINK),
            "PIRL" => Ok(Symbol::PIRL),
            "PIVX" => Ok(Symbol::PIVX),
            "PKB" => Ok(Symbol::PKB),
            "PLBT" => Ok(Symbol::PLBT),
            "PLR" => Ok(Symbol::PLR),
            "POE" => Ok(Symbol::POE),
            "POLL" => Ok(Symbol::POLL),
            "POSW" => Ok(Symbol::POSW),
            "POT" => Ok(Symbol::POT),
            "POWR" => Ok(Symbol::POWR),
            "PPC" => Ok(Symbol::PPC),
            "PPP" => Ok(Symbol::PPP),
            "PPT" => Ok(Symbol::PPT),
            "NET" => Ok(Symbol::NET),
            "PRG" => Ok(Symbol::PRG),
            "PST" => Ok(Symbol::PST),
            "PTC" => Ok(Symbol::PTC),
            "PTOY" => Ok(Symbol::PTOY),
            "PURA" => Ok(Symbol::PURA),
            "QRL" => Ok(Symbol::QRL),
            "QTUM" => Ok(Symbol::QTUM),
            "QWARK" => Ok(Symbol::QWARK),
            "R" => Ok(Symbol::R),
            "RADS" => Ok(Symbol::RADS),
            "RBY" => Ok(Symbol::RBY),
            "RDD" => Ok(Symbol::RDD),
            "REC" => Ok(Symbol::REC),
            "REP" => Ok(Symbol::REP),
            "REQ" => Ok(Symbol::REQ),
            "RHOC" => Ok(Symbol::RHOC),
            "RIC" => Ok(Symbol::RIC),
            "RISE" => Ok(Symbol::RISE),
            "RLC" => Ok(Symbol::RLC),
            "RPX" => Ok(Symbol::RPX),
            "RVT" => Ok(Symbol::RVT),
            "SALT" => Ok(Symbol::SALT),
            "SAN" => Ok(Symbol::SAN),
            "SBD" => Ok(Symbol::SBD),
            "SC" => Ok(Symbol::SC),
            "SEQ" => Ok(Symbol::SEQ),
            "SHIFT" => Ok(Symbol::SHIFT),
            "SIB" => Ok(Symbol::SIB),
            "SKY" => Ok(Symbol::SKY),
            "SLR" => Ok(Symbol::SLR),
            "SLS" => Ok(Symbol::SLS),
            "SNC" => Ok(Symbol::SNC),
            "SNGLS" => Ok(Symbol::SNGLS),
            "SNM" => Ok(Symbol::SNM),
            "SNRG" => Ok(Symbol::SNRG),
            "SNT" => Ok(Symbol::SNT),
            "SOAR" => Ok(Symbol::SOAR),
            "SPHR" => Ok(Symbol::SPHR),
            "QBT" => Ok(Symbol::QBT),
            "SPR" => Ok(Symbol::SPR),
            "START" => Ok(Symbol::START),
            "STEEM" => Ok(Symbol::STEEM),
            "STORJ" => Ok(Symbol::STORJ),
            "STRAT" => Ok(Symbol::STRAT),
            "STX" => Ok(Symbol::STX),
            "SUB" => Ok(Symbol::SUB),
            "SUMO" => Ok(Symbol::SUMO),
            "RCN" => Ok(Symbol::RCN),
            "SWIFT" => Ok(Symbol::SWIFT),
            "SWT" => Ok(Symbol::SWT),
            "SXC" => Ok(Symbol::SXC),
            "SYNX" => Ok(Symbol::SYNX),
            "SYS" => Ok(Symbol::SYS),
            "TAAS" => Ok(Symbol::TAAS),
            "THC" => Ok(Symbol::THC),
            "THS" => Ok(Symbol::THS),
            "TIME" => Ok(Symbol::TIME),
            "TKN" => Ok(Symbol::TKN),
            "TKS" => Ok(Symbol::TKS),
            "TNT" => Ok(Symbol::TNT),
            "TRIG" => Ok(Symbol::TRIG),
            "TRST" => Ok(Symbol::TRST),
            "TRX" => Ok(Symbol::TRX),
            "TX" => Ok(Symbol::TX),
            "UBQ" => Ok(Symbol::UBQ),
            "UGT" => Ok(Symbol::UGT),
            "UNB" => Ok(Symbol::UNB),
            "UNIT" => Ok(Symbol::UNIT),
            "SMART" => Ok(Symbol::SMART),
            "USDT" => Ok(Symbol::USDT),
            "USNBT" => Ok(Symbol::USNBT),
            "VERI" => Ok(Symbol::VERI),
            "VIA" => Ok(Symbol::VIA),
            "VIB" => Ok(Symbol::VIB),
            "VIBE" => Ok(Symbol::VIBE),
            "VOISE" => Ok(Symbol::VOISE),
            "VOX" => Ok(Symbol::VOX),
            "VRC" => Ok(Symbol::VRC),
            "VRM" => Ok(Symbol::VRM),
            "VTC" => Ok(Symbol::VTC),
            "VTR" => Ok(Symbol::VTR),
            "WAVES" => Ok(Symbol::WAVES),
            "WCT" => Ok(Symbol::WCT),
            "WGR" => Ok(Symbol::WGR),
            "WHL" => Ok(Symbol::WHL),
            "WINGS" => Ok(Symbol::WINGS),
            "WTC" => Ok(Symbol::WTC),
            "WTT" => Ok(Symbol::WTT),
            "XAS" => Ok(Symbol::XAS),
            "XAUR" => Ok(Symbol::XAUR),
            "XBC" => Ok(Symbol::XBC),
            "XBY" => Ok(Symbol::XBY),
            "XCP" => Ok(Symbol::XCP),
            "XDN" => Ok(Symbol::XDN),
            "XEL" => Ok(Symbol::XEL),
            "XEM" => Ok(Symbol::XEM),
            "XIN" => Ok(Symbol::XIN),
            "XLM" => Ok(Symbol::XLM),
            "XLR" => Ok(Symbol::XLR),
            "XMCC" => Ok(Symbol::XMCC),
            "XMG" => Ok(Symbol::XMG),
            "XMR" => Ok(Symbol::XMR),
            "XMY" => Ok(Symbol::XMY),
            "XP" => Ok(Symbol::XP),
            "XPM" => Ok(Symbol::XPM),
            "XRB" => Ok(Symbol::XRB),
            "XRL" => Ok(Symbol::XRL),
            "XSH" => Ok(Symbol::XSH),
            "XSPEC" => Ok(Symbol::XSPEC),
            "XST" => Ok(Symbol::XST),
            "XTZ" => Ok(Symbol::XTZ),
            "XUC" => Ok(Symbol::XUC),
            "XVC" => Ok(Symbol::XVC),
            "XVG" => Ok(Symbol::XVG),
            "XWC" => Ok(Symbol::XWC),
            "XZC" => Ok(Symbol::XZC),
            "YOYOW" => Ok(Symbol::YOYOW),
            "ZCL" => Ok(Symbol::ZCL),
            "ZEN" => Ok(Symbol::ZEN),
            "ZER" => Ok(Symbol::ZER),
            "ZNY" => Ok(Symbol::ZNY),
            "ZOI" => Ok(Symbol::ZOI),
            "ZRC" => Ok(Symbol::ZRC),
            "ZRX" => Ok(Symbol::ZRX),
            "ZSC" => Ok(Symbol::ZSC),
            "ELTCOIN" => Ok(Symbol::ELTCOIN),
            "PURE" => Ok(Symbol::PURE),
            "DSR" => Ok(Symbol::DSR),
            "UKG" => Ok(Symbol::UKG),
            "AI" => Ok(Symbol::AI),
            "ALQO" => Ok(Symbol::ALQO),
            "AMM" => Ok(Symbol::AMM),
            "ARN" => Ok(Symbol::ARN),
            "BCD" => Ok(Symbol::BCD),
            "BCX" => Ok(Symbol::BCX),
            "BIX" => Ok(Symbol::BIX),
            "BNTY" => Ok(Symbol::BNTY),
            "BOT" => Ok(Symbol::BOT),
            "BRD" => Ok(Symbol::BRD),
            "BTCA" => Ok(Symbol::BTCA),
            "BTE" => Ok(Symbol::BTE),
            "BWK" => Ok(Symbol::BWK),
            "CAPP" => Ok(Symbol::CAPP),
            "CRC" => Ok(Symbol::CRC),
            "CRED" => Ok(Symbol::CRED),
            "DAI" => Ok(Symbol::DAI),
            "DAT" => Ok(Symbol::DAT),
            "DAV" => Ok(Symbol::DAV),
            "DEW" => Ok(Symbol::DEW),
            "DIM" => Ok(Symbol::DIM),
            "DIVX" => Ok(Symbol::DIVX),
            "DNA" => Ok(Symbol::DNA),
            "DPY" => Ok(Symbol::DPY),
            "DRGN" => Ok(Symbol::DRGN),
            "DTR" => Ok(Symbol::DTR),
            "EAG" => Ok(Symbol::EAG),
            "ELF" => Ok(Symbol::ELF),
            "ETHOS" => Ok(Symbol::ETHOS),
            "FIL" => Ok(Symbol::FIL),
            "FLIXX" => Ok(Symbol::FLIXX),
            "GBX" => Ok(Symbol::GBX),
            "GNX" => Ok(Symbol::GNX),
            "GRX" => Ok(Symbol::GRX),
            "GTO" => Ok(Symbol::GTO),
            "GVT" => Ok(Symbol::GVT),
            "HAT" => Ok(Symbol::HAT),
            "HST" => Ok(Symbol::HST),
            "HWC" => Ok(Symbol::HWC),
            "INK" => Ok(Symbol::INK),
            "INN" => Ok(Symbol::INN),
            "ITC" => Ok(Symbol::ITC),
            "ITNS" => Ok(Symbol::ITNS),
            "LEND" => Ok(Symbol::LEND),
            "MAG" => Ok(Symbol::MAG),
            "MAGE" => Ok(Symbol::MAGE),
            "MDS" => Ok(Symbol::MDS),
            "MED" => Ok(Symbol::MED),
            "MKR" => Ok(Symbol::MKR),
            "MONK" => Ok(Symbol::MONK),
            "NGC" => Ok(Symbol::NGC),
            "OST" => Ok(Symbol::OST),
            "PBL" => Ok(Symbol::PBL),
            "PFR" => Ok(Symbol::PFR),
            "PHR" => Ok(Symbol::PHR),
            "PRL" => Ok(Symbol::PRL),
            "QASH" => Ok(Symbol::QASH),
            "QSP" => Ok(Symbol::QSP),
            "RDN" => Ok(Symbol::RDN),
            "SAGA" => Ok(Symbol::SAGA),
            "SBC" => Ok(Symbol::SBC),
            "SBTC" => Ok(Symbol::SBTC),
            "SMT" => Ok(Symbol::SMT),
            "SNOV" => Ok(Symbol::SNOV),
            "SPANK" => Ok(Symbol::SPANK),
            "SPF" => Ok(Symbol::SPF),
            "SPHTX" => Ok(Symbol::SPHTX),
            "SRN" => Ok(Symbol::SRN),
            "STC" => Ok(Symbol::STC),
            "STORM" => Ok(Symbol::STORM),
            "TIX" => Ok(Symbol::TIX),
            "TNB" => Ok(Symbol::TNB),
            "TSL" => Ok(Symbol::TSL),
            "XID" => Ok(Symbol::XID),
            "UBTC" => Ok(Symbol::UBTC),
            "UQC" => Ok(Symbol::UQC),
            "VEE" => Ok(Symbol::VEE),
            "VET" => Ok(Symbol::VET),
            "VIU" => Ok(Symbol::VIU),
            "WABI" => Ok(Symbol::WABI),
            "WAX" => Ok(Symbol::WAX),
            "WC" => Ok(Symbol::WC),
            "WISH" => Ok(Symbol::WISH),
            "WRC" => Ok(Symbol::WRC),
            "XCPO" => Ok(Symbol::XCPO),
            _ => Err(ErrorKind::UnknownCurrency(name.to_owned()).into()),
        }
    }
}

impl ::std::fmt::Debug for Symbol {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        let symbol = match self {
            &Symbol::EUR => "EUR",
            &Symbol::USD => "USD",
            &Symbol::BTC => "BTC",
            &Symbol::ETH => "ETH",
            &Symbol::ETC => "ETC",
            &Symbol::XRP => "XRP",
            &Symbol::ZEC => "ZEC",
            &Symbol::BCH => "BCH",
            &Symbol::LTC => "LTC",
            &Symbol::ABY => "ABY",
            &Symbol::ACT => "ACT",
            &Symbol::ADA => "ADA",
            &Symbol::ADT => "ADT",
            &Symbol::ADX => "ADX",
            &Symbol::AE => "AE",
            &Symbol::AEON => "AEON",
            &Symbol::AGRS => "AGRS",
            &Symbol::AION => "AION",
            &Symbol::AIR => "AIR",
            &Symbol::ALIS => "ALIS",
            &Symbol::AMB => "AMB",
            &Symbol::AMP => "AMP",
            &Symbol::ANT => "ANT",
            &Symbol::ARDR => "ARDR",
            &Symbol::ARK => "ARK",
            &Symbol::AST => "AST",
            &Symbol::ATB => "ATB",
            &Symbol::ATMC => "ATMC",
            &Symbol::AUR => "AUR",
            &Symbol::AVT => "AVT",
            &Symbol::B2X => "B2X",
            &Symbol::BAY => "BAY",
            &Symbol::BAT => "BAT",
            &Symbol::BCC => "BCC",
            &Symbol::BCN => "BCN",
            &Symbol::BCO => "BCO",
            &Symbol::BCPT => "BCPT",
            &Symbol::BCY => "BCY",
            &Symbol::BDL => "BDL",
            &Symbol::BELA => "BELA",
            &Symbol::BIS => "BIS",
            &Symbol::BITB => "BITB",
            &Symbol::BITCNY => "BITCNY",
            &Symbol::BITUSD => "BITUSD",
            &Symbol::BLITZ => "BLITZ",
            &Symbol::BLK => "BLK",
            &Symbol::BLOCK => "BLOCK",
            &Symbol::BMC => "BMC",
            &Symbol::BNB => "BNB",
            &Symbol::BNT => "BNT",
            &Symbol::BRK => "BRK",
            &Symbol::BSD => "BSD",
            &Symbol::BSR => "BSR",
            &Symbol::BT2 => "BT2",
            &Symbol::BTCD => "BTCD",
            &Symbol::BTS => "BTS",
            &Symbol::BTU => "BTU",
            &Symbol::BTX => "BTX",
            &Symbol::BURST => "BURST",
            &Symbol::BYC => "BYC",
            &Symbol::BTG => "BTG",
            &Symbol::BTM => "BTM",
            &Symbol::CAG => "CAG",
            &Symbol::CANN => "CANN",
            &Symbol::CCT => "CCT",
            &Symbol::CDT => "CDT",
            &Symbol::CFI => "CFI",
            &Symbol::CHC => "CHC",
            &Symbol::CLAM => "CLAM",
            &Symbol::CLOAK => "CLOAK",
            &Symbol::CLUB => "CLUB",
            &Symbol::CAT => "CAT",
            &Symbol::CND => "CND",
            &Symbol::CNX => "CNX",
            &Symbol::COB => "COB",
            &Symbol::COLX => "COLX",
            &Symbol::COSS => "COSS",
            &Symbol::COVAL => "COVAL",
            &Symbol::CPC => "CPC",
            &Symbol::CRB => "CRB",
            &Symbol::CRW => "CRW",
            &Symbol::CMT => "CMT",
            &Symbol::CSNO => "CSNO",
            &Symbol::CTR => "CTR",
            &Symbol::CURE => "CURE",
            &Symbol::CV2 => "CV2",
            &Symbol::CVC => "CVC",
            &Symbol::DASH => "DASH",
            &Symbol::DATA => "DATA",
            &Symbol::DBIX => "DBIX",
            &Symbol::DCN => "DCN",
            &Symbol::DCR => "DCR",
            &Symbol::DCT => "DCT",
            &Symbol::DENT => "DENT",
            &Symbol::DFT => "DFT",
            &Symbol::DGB => "DGB",
            &Symbol::DGD => "DGD",
            &Symbol::DIME => "DIME",
            &Symbol::DLT => "DLT",
            &Symbol::DMD => "DMD",
            &Symbol::DNT => "DNT",
            &Symbol::DOGE => "DOGE",
            &Symbol::DOPE => "DOPE",
            &Symbol::DOT => "DOT",
            &Symbol::DTB => "DTB",
            &Symbol::DYN => "DYN",
            &Symbol::EBST => "EBST",
            &Symbol::ECA => "ECA",
            &Symbol::EDG => "EDG",
            &Symbol::EDO => "EDO",
            &Symbol::EDR => "EDR",
            &Symbol::EFL => "EFL",
            &Symbol::EGC => "EGC",
            &Symbol::ELIX => "ELIX",
            &Symbol::EMC => "EMC",
            &Symbol::EMC2 => "EMC2",
            &Symbol::ENG => "ENG",
            &Symbol::ENJ => "ENJ",
            &Symbol::ENRG => "ENRG",
            &Symbol::EOS => "EOS",
            &Symbol::ERC => "ERC",
            &Symbol::ESP => "ESP",
            &Symbol::ETHD => "ETHD",
            &Symbol::ETN => "ETN",
            &Symbol::ETP => "ETP",
            &Symbol::EVX => "EVX",
            &Symbol::EXCL => "EXCL",
            &Symbol::EXP => "EXP",
            &Symbol::FCT => "FCT",
            &Symbol::FLDC => "FLDC",
            &Symbol::FLO => "FLO",
            &Symbol::FRGC => "FRGC",
            &Symbol::FRST => "FRST",
            &Symbol::FTC => "FTC",
            &Symbol::FUEL => "FUEL",
            &Symbol::FUN => "FUN",
            &Symbol::FYP => "FYP",
            &Symbol::GAM => "GAM",
            &Symbol::GAME => "GAME",
            &Symbol::GAS => "GAS",
            &Symbol::GBG => "GBG",
            &Symbol::GBYTE => "GBYTE",
            &Symbol::GCR => "GCR",
            &Symbol::GEO => "GEO",
            &Symbol::GLD => "GLD",
            &Symbol::GNO => "GNO",
            &Symbol::GNT => "GNT",
            &Symbol::GOLOS => "GOLOS",
            &Symbol::GRC => "GRC",
            &Symbol::GRS => "GRS",
            &Symbol::GUP => "GUP",
            &Symbol::GXS => "GXS",
            &Symbol::HDG => "HDG",
            &Symbol::HMQ => "HMQ",
            &Symbol::HSR => "HSR",
            &Symbol::HUSH => "HUSH",
            &Symbol::HVN => "HVN",
            &Symbol::IFT => "IFT",
            &Symbol::INCNT => "INCNT",
            &Symbol::IND => "IND",
            &Symbol::INF => "INF",
            &Symbol::INFX => "INFX",
            &Symbol::IOC => "IOC",
            &Symbol::ION => "ION",
            &Symbol::IOP => "IOP",
            &Symbol::IXT => "IXT",
            &Symbol::KCS => "KCS",
            &Symbol::KICK => "KICK",
            &Symbol::KIN => "KIN",
            &Symbol::KLN => "KLN",
            &Symbol::KMD => "KMD",
            &Symbol::KORE => "KORE",
            &Symbol::LA => "LA",
            &Symbol::LBC => "LBC",
            &Symbol::LGD => "LGD",
            &Symbol::LINDA => "LINDA",
            &Symbol::LINK => "LINK",
            &Symbol::LKK => "LKK",
            &Symbol::LLT => "LLT",
            &Symbol::LMC => "LMC",
            &Symbol::ICN => "ICN",
            &Symbol::LRC => "LRC",
            &Symbol::LSK => "LSK",
            &Symbol::LUN => "LUN",
            &Symbol::LUX => "LUX",
            &Symbol::MAID => "MAID",
            &Symbol::MANA => "MANA",
            &Symbol::MARS => "MARS",
            &Symbol::MBRS => "MBRS",
            &Symbol::MCAP => "MCAP",
            &Symbol::MCO => "MCO",
            &Symbol::MDA => "MDA",
            &Symbol::MEME => "MEME",
            &Symbol::MER => "MER",
            &Symbol::MGO => "MGO",
            &Symbol::MINT => "MINT",
            &Symbol::MIOTA => "MIOTA",
            &Symbol::MLN => "MLN",
            &Symbol::MNX => "MNX",
            &Symbol::MOD => "MOD",
            &Symbol::MOIN => "MOIN",
            &Symbol::MONA => "MONA",
            &Symbol::MOON => "MOON",
            &Symbol::KNC => "KNC",
            &Symbol::MRT => "MRT",
            &Symbol::MSP => "MSP",
            &Symbol::MTH => "MTH",
            &Symbol::MTL => "MTL",
            &Symbol::MUE => "MUE",
            &Symbol::MUSIC => "MUSIC",
            &Symbol::MYST => "MYST",
            &Symbol::NAS => "NAS",
            &Symbol::NAV => "NAV",
            &Symbol::NEBL => "NEBL",
            &Symbol::NEO => "NEO",
            &Symbol::NEOS => "NEOS",
            &Symbol::NLC2 => "NLC2",
            &Symbol::NLG => "NLG",
            &Symbol::NMC => "NMC",
            &Symbol::NMR => "NMR",
            &Symbol::NULS => "NULS",
            &Symbol::NVC => "NVC",
            &Symbol::NXC => "NXC",
            &Symbol::NXS => "NXS",
            &Symbol::NXT => "NXT",
            &Symbol::OAX => "OAX",
            &Symbol::OCT => "OCT",
            &Symbol::ODN => "ODN",
            &Symbol::OK => "OK",
            &Symbol::OMG => "OMG",
            &Symbol::OMNI => "OMNI",
            &Symbol::ONION => "ONION",
            &Symbol::ORME => "ORME",
            &Symbol::OTN => "OTN",
            &Symbol::PAC => "PAC",
            &Symbol::PART => "PART",
            &Symbol::PASC => "PASC",
            &Symbol::PAY => "PAY",
            &Symbol::PBT => "PBT",
            &Symbol::PDC => "PDC",
            &Symbol::PEC => "PEC",
            &Symbol::PEPECASH => "PEPECASH",
            &Symbol::PINK => "PINK",
            &Symbol::PIRL => "PIRL",
            &Symbol::PIVX => "PIVX",
            &Symbol::PKB => "PKB",
            &Symbol::PLBT => "PLBT",
            &Symbol::PLR => "PLR",
            &Symbol::POE => "POE",
            &Symbol::POLL => "POLL",
            &Symbol::POSW => "POSW",
            &Symbol::POT => "POT",
            &Symbol::POWR => "POWR",
            &Symbol::PPC => "PPC",
            &Symbol::PPP => "PPP",
            &Symbol::PPT => "PPT",
            &Symbol::NET => "NET",
            &Symbol::PRG => "PRG",
            &Symbol::PST => "PST",
            &Symbol::PTC => "PTC",
            &Symbol::PTOY => "PTOY",
            &Symbol::PURA => "PURA",
            &Symbol::QRL => "QRL",
            &Symbol::QTUM => "QTUM",
            &Symbol::QWARK => "QWARK",
            &Symbol::R => "R",
            &Symbol::RADS => "RADS",
            &Symbol::RBY => "RBY",
            &Symbol::RDD => "RDD",
            &Symbol::REC => "REC",
            &Symbol::REP => "REP",
            &Symbol::REQ => "REQ",
            &Symbol::RHOC => "RHOC",
            &Symbol::RIC => "RIC",
            &Symbol::RISE => "RISE",
            &Symbol::RLC => "RLC",
            &Symbol::RPX => "RPX",
            &Symbol::RVT => "RVT",
            &Symbol::SALT => "SALT",
            &Symbol::SAN => "SAN",
            &Symbol::SBD => "SBD",
            &Symbol::SC => "SC",
            &Symbol::SEQ => "SEQ",
            &Symbol::SHIFT => "SHIFT",
            &Symbol::SIB => "SIB",
            &Symbol::SKY => "SKY",
            &Symbol::SLR => "SLR",
            &Symbol::SLS => "SLS",
            &Symbol::SNC => "SNC",
            &Symbol::SNGLS => "SNGLS",
            &Symbol::SNM => "SNM",
            &Symbol::SNRG => "SNRG",
            &Symbol::SNT => "SNT",
            &Symbol::SOAR => "SOAR",
            &Symbol::SPHR => "SPHR",
            &Symbol::QBT => "QBT",
            &Symbol::SPR => "SPR",
            &Symbol::START => "START",
            &Symbol::STEEM => "STEEM",
            &Symbol::STORJ => "STORJ",
            &Symbol::STRAT => "STRAT",
            &Symbol::STX => "STX",
            &Symbol::SUB => "SUB",
            &Symbol::SUMO => "SUMO",
            &Symbol::RCN => "RCN",
            &Symbol::SWIFT => "SWIFT",
            &Symbol::SWT => "SWT",
            &Symbol::SXC => "SXC",
            &Symbol::SYNX => "SYNX",
            &Symbol::SYS => "SYS",
            &Symbol::TAAS => "TAAS",
            &Symbol::THC => "THC",
            &Symbol::THS => "THS",
            &Symbol::TIME => "TIME",
            &Symbol::TKN => "TKN",
            &Symbol::TKS => "TKS",
            &Symbol::TNT => "TNT",
            &Symbol::TRIG => "TRIG",
            &Symbol::TRST => "TRST",
            &Symbol::TRX => "TRX",
            &Symbol::TX => "TX",
            &Symbol::UBQ => "UBQ",
            &Symbol::UGT => "UGT",
            &Symbol::UNB => "UNB",
            &Symbol::UNIT => "UNIT",
            &Symbol::SMART => "SMART",
            &Symbol::USDT => "USDT",
            &Symbol::USNBT => "USNBT",
            &Symbol::VERI => "VERI",
            &Symbol::VIA => "VIA",
            &Symbol::VIB => "VIB",
            &Symbol::VIBE => "VIBE",
            &Symbol::VOISE => "VOISE",
            &Symbol::VOX => "VOX",
            &Symbol::VRC => "VRC",
            &Symbol::VRM => "VRM",
            &Symbol::VTC => "VTC",
            &Symbol::VTR => "VTR",
            &Symbol::WAVES => "WAVES",
            &Symbol::WCT => "WCT",
            &Symbol::WGR => "WGR",
            &Symbol::WHL => "WHL",
            &Symbol::WINGS => "WINGS",
            &Symbol::WTC => "WTC",
            &Symbol::WTT => "WTT",
            &Symbol::XAS => "XAS",
            &Symbol::XAUR => "XAUR",
            &Symbol::XBC => "XBC",
            &Symbol::XBY => "XBY",
            &Symbol::XCP => "XCP",
            &Symbol::XDN => "XDN",
            &Symbol::XEL => "XEL",
            &Symbol::XEM => "XEM",
            &Symbol::XIN => "XIN",
            &Symbol::XLM => "XLM",
            &Symbol::XLR => "XLR",
            &Symbol::XMCC => "XMCC",
            &Symbol::XMG => "XMG",
            &Symbol::XMR => "XMR",
            &Symbol::XMY => "XMY",
            &Symbol::XP => "XP",
            &Symbol::XPM => "XPM",
            &Symbol::XRB => "XRB",
            &Symbol::XRL => "XRL",
            &Symbol::XSH => "XSH",
            &Symbol::XSPEC => "XSPEC",
            &Symbol::XST => "XST",
            &Symbol::XTZ => "XTZ",
            &Symbol::XUC => "XUC",
            &Symbol::XVC => "XVC",
            &Symbol::XVG => "XVG",
            &Symbol::XWC => "XWC",
            &Symbol::XZC => "XZC",
            &Symbol::YOYOW => "YOYOW",
            &Symbol::ZCL => "ZCL",
            &Symbol::ZEN => "ZEN",
            &Symbol::ZER => "ZER",
            &Symbol::ZNY => "ZNY",
            &Symbol::ZOI => "ZOI",
            &Symbol::ZRC => "ZRC",
            &Symbol::ZRX => "ZRX",
            &Symbol::ZSC => "ZSC",
            &Symbol::ELTCOIN => "ELTCOIN",
            &Symbol::PURE => "PURE",
            &Symbol::DSR => "DSR",
            &Symbol::UKG => "UKG",
            &Symbol::AI => "AI",
            &Symbol::ALQO => "ALQO",
            &Symbol::AMM => "AMM",
            &Symbol::ARN => "ARN",
            &Symbol::BCD => "BCD",
            &Symbol::BCX => "BCX",
            &Symbol::BIX => "BIX",
            &Symbol::BNTY => "BNTY",
            &Symbol::BOT => "BOT",
            &Symbol::BRD => "BRD",
            &Symbol::BTCA => "BTCA",
            &Symbol::BTE => "BTE",
            &Symbol::BWK => "BWK",
            &Symbol::CAPP => "CAPP",
            &Symbol::CRC => "CRC",
            &Symbol::CRED => "CRED",
            &Symbol::DAI => "DAI",
            &Symbol::DAT => "DAT",
            &Symbol::DAV => "DAV",
            &Symbol::DEW => "DEW",
            &Symbol::DIM => "DIM",
            &Symbol::DIVX => "DIVX",
            &Symbol::DNA => "DNA",
            &Symbol::DPY => "DPY",
            &Symbol::DRGN => "DRGN",
            &Symbol::DTR => "DTR",
            &Symbol::EAG => "EAG",
            &Symbol::ELF => "ELF",
            &Symbol::ETHOS => "ETHOS",
            &Symbol::FIL => "FIL",
            &Symbol::FLIXX => "FLIXX",
            &Symbol::GBX => "GBX",
            &Symbol::GNX => "GNX",
            &Symbol::GRX => "GRX",
            &Symbol::GTO => "GTO",
            &Symbol::GVT => "GVT",
            &Symbol::HAT => "HAT",
            &Symbol::HST => "HST",
            &Symbol::HWC => "HWC",
            &Symbol::INK => "INK",
            &Symbol::INN => "INN",
            &Symbol::ITC => "ITC",
            &Symbol::ITNS => "ITNS",
            &Symbol::LEND => "LEND",
            &Symbol::MAG => "MAG",
            &Symbol::MAGE => "MAGE",
            &Symbol::MDS => "MDS",
            &Symbol::MED => "MED",
            &Symbol::MKR => "MKR",
            &Symbol::MONK => "MONK",
            &Symbol::NGC => "NGC",
            &Symbol::OST => "OST",
            &Symbol::PBL => "PBL",
            &Symbol::PFR => "PFR",
            &Symbol::PHR => "PHR",
            &Symbol::PRL => "PRL",
            &Symbol::QASH => "QASH",
            &Symbol::QSP => "QSP",
            &Symbol::RDN => "RDN",
            &Symbol::SAGA => "SAGA",
            &Symbol::SBC => "SBC",
            &Symbol::SBTC => "SBTC",
            &Symbol::SMT => "SMT",
            &Symbol::SNOV => "SNOV",
            &Symbol::SPANK => "SPANK",
            &Symbol::SPF => "SPF",
            &Symbol::SPHTX => "SPHTX",
            &Symbol::SRN => "SRN",
            &Symbol::STC => "STC",
            &Symbol::STORM => "STORM",
            &Symbol::TIX => "TIX",
            &Symbol::TNB => "TNB",
            &Symbol::TSL => "TSL",
            &Symbol::XID => "XID",
            &Symbol::UBTC => "UBTC",
            &Symbol::UQC => "UQC",
            &Symbol::VEE => "VEE",
            &Symbol::VET => "VET",
            &Symbol::VIU => "VIU",
            &Symbol::WABI => "WABI",
            &Symbol::WAX => "WAX",
            &Symbol::WC => "WC",
            &Symbol::WISH => "WISH",
            &Symbol::WRC => "WRC",
            &Symbol::XCPO => "XCPO",
        };
        f.write_str(symbol)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn symbol_debug() {
        let c = Symbol::try_from("BTC").unwrap();
        assert_eq!("BTC".to_owned(), format!("{:?}", c));
    }
}
