// Currency symbols utilities.
// SEE: tools/update-coins/symbols.rs.tmpl
// @autogenerated

use std::convert::TryFrom;

use super::errors::{Error, ErrorKind};

/// Currency symbol.
#[derive(Serialize, Deserialize, PartialEq, Clone)]
pub enum Currency {
    /// Euro
    EUR = 1,
    /// United States Dollar
    USD = 2,
    /// Bitcoin
    BTC = 3,
    /// Ethereum
    ETH = 4,
    /// Ethereum Classic
    ETC = 5,
    /// Ripple
    XRP = 6,
    /// Zcash
    ZEC = 7,
    /// Bitcoin Cash
    BCH = 8,
    /// Litecoin
    LTC = 9,
    /// Ace
    ACE = 10,
    /// ArtByte
    ABY = 12,
    /// Achain
    ACT = 19,
    /// Cardano
    ADA = 20,
    /// Animecoin
    ANI = 21,
    /// APX
    APX = 22,
    /// adToken
    ADT = 26,
    /// AdEx
    ADX = 27,
    /// ATMChain
    ATM = 28,
    /// Aeternity
    AE = 29,
    /// Aeon
    AEON = 30,
    /// Atmos
    ATMS = 31,
    /// Agoras Tokens
    AGRS = 32,
    /// Atomic Coin
    ATOM = 33,
    /// Authorship
    ATS = 34,
    /// Aion
    AION = 35,
    /// AirToken
    AIR = 36,
    /// B3Coin
    B3 = 37,
    /// ALIS
    ALIS = 38,
    /// BitBoost
    BBT = 39,
    /// BlockCDN
    BCDN = 42,
    /// Ambrosus
    AMB = 43,
    /// Synereo
    AMP = 47,
    /// Aragon
    ANT = 51,
    /// BestChain
    BEST = 52,
    /// DAO.Casino
    BET = 53,
    /// BigONE Token
    BIG = 54,
    /// Ardor
    ARDR = 59,
    /// BLUE
    BLUE = 62,
    /// Ark
    ARK = 63,
    /// BnrtxCoin
    BNX = 67,
    /// AirSwap
    AST = 68,
    /// ATBCoin
    ATB = 69,
    /// Breakout Stake
    BRX = 71,
    /// ATMCoin
    ATMC = 73,
    /// BitcoinZ
    BTCZ = 77,
    /// Auroracoin
    AUR = 79,
    /// Aventus
    AVT = 82,
    /// BuzzCoin
    BUZZ = 83,
    /// SegWit2x [Futures]
    B2X = 85,
    /// BitBay
    BAY = 90,
    /// Confido
    CFD = 91,
    /// Basic Attention Token
    BAT = 92,
    /// Cryptojacks
    CJ = 93,
    /// BitConnect
    BCC = 94,
    /// Bytecoin
    BCN = 97,
    /// BridgeCoin
    BCO = 98,
    /// BlockMason Credit Protocol
    BCPT = 99,
    /// Bitcrystals
    BCY = 100,
    /// Bitdeal
    BDL = 101,
    /// Bela
    BELA = 102,
    /// CampusCoin
    CMPCO = 103,
    /// BitCoal
    COAL = 104,
    /// Cryptopay
    CPAY = 105,
    /// Bismuth
    BIS = 112,
    /// BitBean
    BITB = 114,
    /// bitCNY
    BITCNY = 117,
    /// DaxxCoin
    DAXX = 119,
    /// DeepBrain Chain
    DBC = 120,
    /// DecentBet
    DBET = 121,
    /// bitUSD
    BITUSD = 123,
    /// Dinastycoin
    DCY = 126,
    /// Blitzcash
    BLITZ = 128,
    /// BlackCoin
    BLK = 129,
    /// Blocknet
    BLOCK = 131,
    /// Dix Asset
    DIX = 134,
    /// Blackmoon Crypto
    BMC = 138,
    /// Binance Coin
    BNB = 139,
    /// Bancor
    BNT = 140,
    /// Denarius
    DNR = 141,
    /// Dovu
    DOVU = 143,
    /// DigitalPrice
    DP = 144,
    /// DCORP
    DRP = 147,
    /// EarthCoin
    EAC = 151,
    /// Breakout
    BRK = 154,
    /// ECC
    ECC = 155,
    /// BitSend
    BSD = 158,
    /// BitSoar
    BSR = 160,
    /// Ellaism
    ELLA = 162,
    /// BitcoinDark
    BTCD = 168,
    /// ENTCash
    ENT = 169,
    /// Eroscoin
    ERO = 172,
    /// Escroco
    ESC = 173,
    /// BitShares
    BTS = 176,
    /// Bitcore
    BTX = 180,
    /// EXRNchain
    EXRN = 184,
    /// Burst
    BURST = 185,
    /// FairCoin
    FAIR = 186,
    /// FujiCoin
    FJC = 188,
    /// Flash
    FLASH = 189,
    /// Bytecent
    BYC = 190,
    /// Bitcoin Gold
    BTG = 192,
    /// FlutterCoin
    FLT = 193,
    /// Change
    CAG = 195,
    /// Fastcoin
    FST = 196,
    /// CannabisCoin
    CANN = 198,
    /// UGAIN
    GAIN = 200,
    /// Global Business Revolution
    GBRC = 205,
    /// CoinDash
    CDT = 210,
    /// Mercury Protocol
    GMT = 211,
    /// Cofound.it
    CFI = 213,
    /// ChainCoin
    CHC = 215,
    /// Grid+
    GRID = 217,
    /// Growers International
    GRWI = 219,
    /// Clams
    CLAM = 220,
    /// Game
    GTC = 221,
    /// CloakCoin
    CLOAK = 222,
    /// ClubCoin
    CLUB = 223,
    /// HomeBlockCoin
    HBC = 228,
    /// Cindicator
    CND = 229,
    /// HelloGold
    HGT = 230,
    /// Hyper Pay
    HPY = 231,
    /// Cryptonex
    CNX = 233,
    /// HTMLCOIN
    HTML = 234,
    /// Cobinhood
    COB = 235,
    /// ColossusCoinXT
    COLX = 236,
    /// HTML5COIN
    HTML5 = 237,
    /// HunterCoin
    HUC = 238,
    /// HyperStake
    HYP = 240,
    /// COSS
    COSS = 241,
    /// ICOS
    ICOS = 242,
    /// Circuits of Value
    COVAL = 243,
    /// ICON
    ICX = 244,
    /// Capricoin
    CPC = 245,
    /// Infinitecoin
    IFC = 246,
    /// Ignis
    IGNIS = 247,
    /// Creditbit
    CRB = 248,
    /// Internxt
    INXT = 253,
    /// Crown
    CRW = 254,
    /// BitDice
    CSNO = 258,
    /// Jinn
    JINN = 260,
    /// Karmacoin
    KARMA = 261,
    /// Centra
    CTR = 262,
    /// Kubera Coin
    KBR = 263,
    /// Curecoin
    CURE = 264,
    /// Civic
    CVC = 266,
    /// KekCoin
    KEK = 267,
    /// Karbo
    KRB = 271,
    /// LanaCoin
    LANA = 273,
    /// Dash
    DASH = 276,
    /// LIFE
    LIFE = 277,
    /// Streamr DATAcoin
    DATA = 278,
    /// Linx
    LINX = 280,
    /// DubaiCoin
    DBIX = 282,
    /// Dentacoin
    DCN = 284,
    /// Decred
    DCR = 285,
    /// LockChain
    LOC = 286,
    /// DECENT
    DCT = 287,
    /// Dent
    DENT = 291,
    /// DigiByte
    DGB = 296,
    /// Megacoin
    MEC = 298,
    /// DigixDAO
    DGD = 299,
    /// Dimecoin
    DIME = 302,
    /// MergeCoin
    MGC = 303,
    /// Agrello
    DLT = 307,
    /// Diamond
    DMD = 310,
    /// district0x
    DNT = 312,
    /// Dogecoin
    DOGE = 313,
    /// Olympus Labs
    MOT = 314,
    /// DopeCoin
    DOPE = 316,
    /// Dotcoin
    DOT = 317,
    /// MyBit Token
    MYB = 320,
    /// MazaCoin
    MZC = 322,
    /// Databits
    DTB = 327,
    /// Neumark
    NEU = 329,
    /// Autonio
    NIO = 331,
    /// Dynamic
    DYN = 332,
    /// NobleCoin
    NOBL = 336,
    /// eBoost
    EBST = 337,
    /// NewYorkCoin
    NYC = 342,
    /// Edgeless
    EDG = 345,
    /// Eidoo
    EDO = 346,
    /// E-Dinar Coin
    EDR = 348,
    /// e-Gulden
    EFL = 350,
    /// Opus
    OPT = 351,
    /// EverGreenCoin
    EGC = 353,
    /// PayPeer
    PAYP = 357,
    /// Elixir
    ELIX = 361,
    /// Piggycoin
    PIGGY = 363,
    /// CryptoPing
    PING = 364,
    /// Emercoin
    EMC = 366,
    /// Einsteinium
    EMC2 = 367,
    /// Lampix
    PIX = 368,
    /// Playkey
    PKT = 370,
    /// Enigma
    ENG = 371,
    /// Enjin Coin
    ENJ = 372,
    /// Energycoin
    ENRG = 373,
    /// HEROcoin
    PLAY = 374,
    /// Pandacoin
    PND = 375,
    /// EOS
    EOS = 376,
    /// EuropeCoin
    ERC = 379,
    /// Espers
    ESP = 382,
    /// Presearch
    PRE = 383,
    /// Ethereum Dark
    ETHD = 385,
    /// Electroneum
    ETN = 386,
    /// Metaverse ETP
    ETP = 387,
    /// Privatix
    PRIX = 388,
    /// Quantum
    QAU = 392,
    /// Everex
    EVX = 394,
    /// ExclusiveCoin
    EXCL = 395,
    /// QLINK
    QLC = 396,
    /// Quark
    QRK = 397,
    /// Expanse
    EXP = 398,
    /// Qvolta
    QVT = 399,
    /// Condensate
    RAIN = 403,
    /// Rimbit
    RBT = 404,
    /// Factom
    FCT = 407,
    /// Royal Kingdom Coin
    RKC = 415,
    /// FoldingCoin
    FLDC = 417,
    /// Russian Miner Coin
    RMC = 418,
    /// FlorinCoin
    FLO = 419,
    /// Rupee
    RUP = 420,
    /// Safe Exchange Coin
    SAFEX = 421,
    /// Fargocoin
    FRGC = 428,
    /// Social
    SCL = 429,
    /// Social Send
    SEND = 430,
    /// FirstCoin
    FRST = 431,
    /// StrongHands
    SHND = 432,
    /// Feathercoin
    FTC = 434,
    /// Etherparty
    FUEL = 436,
    /// FunFair
    FUN = 437,
    /// Gambit
    GAM = 448,
    /// GameCredits
    GAME = 449,
    /// Sprouts
    SPRTS = 450,
    /// Gas
    GAS = 452,
    /// Sharechain
    SSS = 453,
    /// Simple Token
    ST = 454,
    /// STRAKS
    STAK = 455,
    /// Golos Gold
    GBG = 456,
    /// Starbase
    STAR = 457,
    /// Byteball Bytes
    GBYTE = 459,
    /// Global Currency Reserve
    GCR = 461,
    /// GeoCoin
    GEO = 463,
    /// GoldCoin
    GLD = 466,
    /// TrueFlip
    TFL = 470,
    /// Gnosis
    GNO = 471,
    /// Golem
    GNT = 472,
    /// FedoraCoin
    TIPS = 473,
    /// Golos
    GOLOS = 474,
    /// GridCoin
    GRC = 479,
    /// Tokugawa
    TOK = 480,
    /// Terracoin
    TRC = 481,
    /// Groestlcoin
    GRS = 483,
    /// TrumpCoin
    TRUMP = 484,
    /// TrustPlus
    TRUST = 485,
    /// TittieCoin
    TTC = 487,
    /// Matchpool
    GUP = 490,
    /// GXShares
    GXS = 491,
    /// Upfiring
    UFR = 492,
    /// Unitus
    UIS = 493,
    /// Unify
    UNIFY = 496,
    /// Hedge
    HDG = 497,
    /// UTRUST
    UTK = 500,
    /// VPNCoin
    VASH = 501,
    /// VeChain
    VEN = 503,
    /// Humaniq
    HMQ = 506,
    /// VIVO
    VIVO = 509,
    /// Hshare
    HSR = 510,
    /// Hush
    HUSH = 514,
    /// Veros
    VRS = 515,
    /// Hive
    HVN = 516,
    /// Vsync
    VSX = 517,
    /// WorldCoin
    WDC = 523,
    /// Wild Crypto
    WILD = 525,
    /// InvestFeed
    IFT = 532,
    /// Cryptonite
    XCN = 534,
    /// Incent
    INCNT = 536,
    /// Indorse Token
    IND = 537,
    /// CybCSec
    XCS = 538,
    /// InfChain
    INF = 539,
    /// Influxcoin
    INFX = 540,
    /// Footy Cash
    XFT = 541,
    /// XGOX
    XGOX = 542,
    /// I/O Coin
    IOC = 544,
    /// ION
    ION = 545,
    /// Internet of People
    IOP = 546,
    /// LeviarCoin
    XLC = 547,
    /// PetroDollar
    XPD = 553,
    /// iXledger
    IXT = 555,
    /// KuCoin Shares
    KCS = 568,
    /// Zlancer
    ZCG = 569,
    /// ZenGold
    ZENGOLD = 572,
    /// KickCoin
    KICK = 573,
    /// Kin
    KIN = 574,
    /// Kolion
    KLN = 576,
    /// Komodo
    KMD = 577,
    /// Kore
    KORE = 579,
    /// LAToken
    LA = 584,
    /// LBRY Credits
    LBC = 587,
    /// Legends Room
    LGD = 596,
    /// Linda
    LINDA = 598,
    /// ChainLink
    LINK = 599,
    /// Lykke
    LKK = 603,
    /// LLToken
    LLT = 604,
    /// LoMoCoin
    LMC = 605,
    /// Iconomi
    ICN = 608,
    /// Loopring
    LRC = 609,
    /// Lisk
    LSK = 610,
    /// Lunyr
    LUN = 617,
    /// LUXCoin
    LUX = 619,
    /// MaidSafeCoin
    MAID = 624,
    /// Decentraland
    MANA = 625,
    /// MCAP
    MCAP = 636,
    /// Monaco
    MCO = 638,
    /// Moeda Loyalty Points
    MDA = 641,
    /// Memetic / PepeCoin
    MEME = 643,
    /// Mercury
    MER = 646,
    /// MobileGo
    MGO = 650,
    /// Mintcoin
    MINT = 653,
    /// IOTA
    MIOTA = 654,
    /// Melon
    MLN = 656,
    /// MinexCoin
    MNX = 661,
    /// Modum
    MOD = 662,
    /// Moin
    MOIN = 663,
    /// MonaCoin
    MONA = 665,
    /// Mooncoin
    MOON = 668,
    /// Kyber Network
    KNC = 671,
    /// Miners' Reward Token
    MRT = 673,
    /// Mothership
    MSP = 676,
    /// Monetha
    MTH = 678,
    /// Metal
    MTL = 679,
    /// MonetaryUnit
    MUE = 683,
    /// Musicoin
    MUSIC = 685,
    /// Mysterium
    MYST = 688,
    /// Nebulas
    NAS = 692,
    /// NAV Coin
    NAV = 694,
    /// Neblio
    NEBL = 699,
    /// NEO
    NEO = 700,
    /// NeosCoin
    NEOS = 701,
    /// NoLimitCoin
    NLC2 = 706,
    /// Gulden
    NLG = 707,
    /// Namecoin
    NMC = 708,
    /// Numeraire
    NMR = 709,
    /// Nuls
    NULS = 720,
    /// Novacoin
    NVC = 721,
    /// Nexium
    NXC = 723,
    /// Nexus
    NXS = 724,
    /// Nxt
    NXT = 725,
    /// OAX
    OAX = 729,
    /// OracleChain
    OCT = 734,
    /// Obsidian
    ODN = 735,
    /// OKCash
    OK = 738,
    /// OmiseGO
    OMG = 740,
    /// Omni
    OMNI = 741,
    /// DeepOnion
    ONION = 742,
    /// Ormeus Coin
    ORME = 750,
    /// Open Trading Network
    OTN = 752,
    /// PACcoin
    PAC = 755,
    /// Particl
    PART = 757,
    /// Pascal Coin
    PASC = 758,
    /// TenX
    PAY = 760,
    /// Project Decorum
    PDC = 765,
    /// Pepe Cash
    PEPECASH = 768,
    /// PinkCoin
    PINK = 777,
    /// Pirl
    PIRL = 779,
    /// PIVX
    PIVX = 780,
    /// ParkByte
    PKB = 783,
    /// Polybius
    PLBT = 785,
    /// Pillar
    PLR = 787,
    /// Po.et
    POE = 790,
    /// ClearPoll
    POLL = 792,
    /// PoSW Coin
    POSW = 797,
    /// PotCoin
    POT = 798,
    /// Power Ledger
    POWR = 799,
    /// Peercoin
    PPC = 800,
    /// PayPie
    PPP = 801,
    /// Populous
    PPT = 802,
    /// Nimiq
    NET = 803,
    /// Paragon
    PRG = 807,
    /// Primas
    PST = 815,
    /// Pesetacoin
    PTC = 817,
    /// Patientory
    PTOY = 818,
    /// Pura
    PURA = 820,
    /// Quantum Resistant Ledger
    QRL = 835,
    /// Qtum
    QTUM = 837,
    /// Qwark
    QWARK = 839,
    /// Revain
    R = 840,
    /// Radium
    RADS = 841,
    /// Rubycoin
    RBY = 847,
    /// ReddCoin
    RDD = 849,
    /// Regalcoin
    REC = 851,
    /// Augur
    REP = 855,
    /// Request Network
    REQ = 856,
    /// RChain
    RHOC = 860,
    /// Riecoin
    RIC = 861,
    /// Rise
    RISE = 864,
    /// iExec RLC
    RLC = 867,
    /// Red Pulse
    RPX = 873,
    /// Rivetz
    RVT = 880,
    /// SALT
    SALT = 884,
    /// Santiment Network Token
    SAN = 885,
    /// Steem Dollars
    SBD = 887,
    /// Siacoin
    SC = 888,
    /// Sequence
    SEQ = 896,
    /// Shift
    SHIFT = 903,
    /// SIBCoin
    SIB = 906,
    /// Skycoin
    SKY = 916,
    /// SolarCoin
    SLR = 922,
    /// SaluS
    SLS = 923,
    /// SunContract
    SNC = 929,
    /// SingularDTV
    SNGLS = 931,
    /// SONM
    SNM = 932,
    /// Synergy
    SNRG = 933,
    /// Status
    SNT = 934,
    /// Sphere
    SPHR = 944,
    /// Qbao
    QBT = 945,
    /// SpreadCoin
    SPR = 946,
    /// Startcoin
    START = 951,
    /// Steem
    STEEM = 953,
    /// Storj
    STORJ = 956,
    /// Stratis
    STRAT = 957,
    /// Stox
    STX = 961,
    /// Substratum
    SUB = 962,
    /// Sumokoin
    SUMO = 963,
    /// Ripio Credit Network
    RCN = 965,
    /// Bitswift
    SWIFT = 966,
    /// Swarm City
    SWT = 969,
    /// Sexcoin
    SXC = 970,
    /// Syndicate
    SYNX = 972,
    /// Syscoin
    SYS = 973,
    /// TaaS
    TAAS = 974,
    /// HempCoin
    THC = 992,
    /// Chronobank
    TIME = 994,
    /// TokenCard
    TKN = 997,
    /// Tokes
    TKS = 999,
    /// Tierion
    TNT = 1001,
    /// Triggers
    TRIG = 1013,
    /// WeTrust
    TRST = 1016,
    /// TRON
    TRX = 1019,
    /// TransferCoin
    TX = 1024,
    /// Ubiq
    UBQ = 1028,
    /// UG Token
    UGT = 1031,
    /// UnbreakableCoin
    UNB = 1034,
    /// SmartCash
    SMART = 1049,
    /// Tether
    USDT = 1050,
    /// NuBits
    USNBT = 1051,
    /// Veritaseum
    VERI = 1060,
    /// Viacoin
    VIA = 1062,
    /// Viberate
    VIB = 1063,
    /// VIBE
    VIBE = 1064,
    /// Voise
    VOISE = 1071,
    /// Voxels
    VOX = 1073,
    /// VeriCoin
    VRC = 1076,
    /// VeriumReserve
    VRM = 1077,
    /// Vertcoin
    VTC = 1082,
    /// vTorrent
    VTR = 1083,
    /// Waves
    WAVES = 1088,
    /// Waves Community Token
    WCT = 1092,
    /// Wagerr
    WGR = 1097,
    /// Wings
    WINGS = 1101,
    /// Walton
    WTC = 1108,
    /// Asch
    XAS = 1112,
    /// Xaurum
    XAUR = 1114,
    /// Bitcoin Plus
    XBC = 1115,
    /// XTRABYTES
    XBY = 1119,
    /// Counterparty
    XCP = 1123,
    /// DigitalNote
    XDN = 1129,
    /// Elastic
    XEL = 1130,
    /// NEM
    XEM = 1131,
    /// Infinity Economics
    XIN = 1136,
    /// Stellar
    XLM = 1140,
    /// Solaris
    XLR = 1141,
    /// Monoeci
    XMCC = 1142,
    /// Magi
    XMG = 1143,
    /// Monero
    XMR = 1144,
    /// Myriad
    XMY = 1145,
    /// Experience Points
    XP = 1150,
    /// Primecoin
    XPM = 1153,
    /// RaiBlocks
    XRB = 1158,
    /// Rialto
    XRL = 1161,
    /// SHIELD
    XSH = 1163,
    /// Spectrecoin
    XSPEC = 1164,
    /// Stealthcoin
    XST = 1165,
    /// Tezos (Pre-Launch)
    XTZ = 1170,
    /// Exchange Union
    XUC = 1171,
    /// Vcash
    XVC = 1172,
    /// Verge
    XVG = 1174,
    /// WhiteCoin
    XWC = 1176,
    /// ZCoin
    XZC = 1177,
    /// YOYOW
    YOYOW = 1182,
    /// ZClassic
    ZCL = 1185,
    /// ZenCash
    ZEN = 1187,
    /// Zero
    ZER = 1190,
    /// Bitzeny
    ZNY = 1194,
    /// Zoin
    ZOI = 1195,
    /// 0x
    ZRX = 1197,
    /// Zeusshield
    ZSC = 1198,
    /// ELTCOIN
    ELTCOIN = 1202,
    /// Unikoin Gold
    UKG = 1208,
    /// POLY AI
    AI = 1211,
    /// ALQO
    ALQO = 1212,
    /// MicroMoney
    AMM = 1213,
    /// Aeron
    ARN = 1214,
    /// Bitcoin Diamond
    BCD = 1219,
    /// BitcoinX [Futures]
    BCX = 1221,
    /// Bibox Token
    BIX = 1222,
    /// Bounty0x
    BNTY = 1223,
    /// Bodhi
    BOT = 1225,
    /// Bread
    BRD = 1227,
    /// Bitair
    BTCA = 1229,
    /// BitSerial
    BTE = 1230,
    /// Bulwark
    BWK = 1231,
    /// Cappasity
    CAPP = 1232,
    /// CrowdCoin
    CRC = 1235,
    /// Verify
    CRED = 1236,
    /// Dai
    DAI = 1239,
    /// Datum
    DAT = 1240,
    /// DEW
    DEW = 1243,
    /// DIMCOIN
    DIM = 1245,
    /// Divi
    DIVX = 1246,
    /// EncrypGen
    DNA = 1247,
    /// Delphy
    DPY = 1248,
    /// Dragonchain
    DRGN = 1249,
    /// Dynamic Trading Rights
    DTR = 1251,
    /// EA Coin
    EAG = 1252,
    /// aelf
    ELF = 1256,
    /// Ethos
    ETHOS = 1260,
    /// Filecoin [Futures]
    FIL = 1263,
    /// Flixxo
    FLIXX = 1264,
    /// GoByte
    GBX = 1267,
    /// Genaro Network
    GNX = 1269,
    /// GOLD Reward Token
    GRX = 1271,
    /// Gifto
    GTO = 1272,
    /// Genesis Vision
    GVT = 1273,
    /// Hawala.Today
    HAT = 1274,
    /// Decision Token
    HST = 1276,
    /// HollyWoodCoin
    HWC = 1277,
    /// Ink
    INK = 1280,
    /// Innova
    INN = 1281,
    /// IoT Chain
    ITC = 1283,
    /// IntenseCoin
    ITNS = 1284,
    /// ETHLend
    LEND = 1286,
    /// Magnet
    MAG = 1288,
    /// MagicCoin
    MAGE = 1289,
    /// MediShares
    MDS = 1290,
    /// Medibloc
    MED = 1291,
    /// Maker
    MKR = 1292,
    /// NAGA
    NGC = 1297,
    /// Publica
    PBL = 1303,
    /// Payfair
    PFR = 1305,
    /// Phore
    PHR = 1306,
    /// Oyster Pearl
    PRL = 1313,
    /// QASH
    QASH = 1314,
    /// Quantstamp
    QSP = 1315,
    /// Raiden Network Token
    RDN = 1316,
    /// SagaCoin
    SAGA = 1319,
    /// Super Bitcoin
    SBTC = 1321,
    /// SmartMesh
    SMT = 1326,
    /// Snovio
    SNOV = 1327,
    /// SpankChain
    SPANK = 1328,
    /// SportyFi
    SPF = 1329,
    /// SophiaTX
    SPHTX = 1330,
    /// SIRIN LABS Token
    SRN = 1331,
    /// Storm
    STORM = 1336,
    /// Blocktix
    TIX = 1339,
    /// Time New Bank
    TNB = 1340,
    /// Energo
    TSL = 1344,
    /// Sphre AIR
    XID = 1345,
    /// United Bitcoin
    UBTC = 1346,
    /// Uquid Coin
    UQC = 1348,
    /// BLOCKv
    VEE = 1349,
    /// Viuly
    VIU = 1351,
    /// WaBi
    WABI = 1353,
    /// WAX
    WAX = 1354,
    /// WINCOIN
    WC = 1355,
    /// MyWish
    WISH = 1356,
    /// Worldcore
    WRC = 1357,
    /// Copico
    XCPO = 1358,
}

/// Tries to convert string to a currency `Currency`.
impl<'a> TryFrom<&'a str> for Currency {
    type Error = Error;

    fn try_from(name: &str) -> Result<Self, Self::Error> {
        match name {
            "EUR" => Ok(Currency::EUR),
            "USD" => Ok(Currency::USD),
            "BTC" => Ok(Currency::BTC),
            "ETH" => Ok(Currency::ETH),
            "ETC" => Ok(Currency::ETC),
            "XRP" => Ok(Currency::XRP),
            "ZEC" => Ok(Currency::ZEC),
            "BCH" => Ok(Currency::BCH),
            "LTC" => Ok(Currency::LTC),
            "ACE" => Ok(Currency::ACE),
            "ABY" => Ok(Currency::ABY),
            "ACT" => Ok(Currency::ACT),
            "ADA" => Ok(Currency::ADA),
            "ANI" => Ok(Currency::ANI),
            "APX" => Ok(Currency::APX),
            "ADT" => Ok(Currency::ADT),
            "ADX" => Ok(Currency::ADX),
            "ATM" => Ok(Currency::ATM),
            "AE" => Ok(Currency::AE),
            "AEON" => Ok(Currency::AEON),
            "ATMS" => Ok(Currency::ATMS),
            "AGRS" => Ok(Currency::AGRS),
            "ATOM" => Ok(Currency::ATOM),
            "ATS" => Ok(Currency::ATS),
            "AION" => Ok(Currency::AION),
            "AIR" => Ok(Currency::AIR),
            "B3" => Ok(Currency::B3),
            "ALIS" => Ok(Currency::ALIS),
            "BBT" => Ok(Currency::BBT),
            "BCDN" => Ok(Currency::BCDN),
            "AMB" => Ok(Currency::AMB),
            "AMP" => Ok(Currency::AMP),
            "ANT" => Ok(Currency::ANT),
            "BEST" => Ok(Currency::BEST),
            "BET" => Ok(Currency::BET),
            "BIG" => Ok(Currency::BIG),
            "ARDR" => Ok(Currency::ARDR),
            "BLUE" => Ok(Currency::BLUE),
            "ARK" => Ok(Currency::ARK),
            "BNX" => Ok(Currency::BNX),
            "AST" => Ok(Currency::AST),
            "ATB" => Ok(Currency::ATB),
            "BRX" => Ok(Currency::BRX),
            "ATMC" => Ok(Currency::ATMC),
            "BTCZ" => Ok(Currency::BTCZ),
            "AUR" => Ok(Currency::AUR),
            "AVT" => Ok(Currency::AVT),
            "BUZZ" => Ok(Currency::BUZZ),
            "B2X" => Ok(Currency::B2X),
            "BAY" => Ok(Currency::BAY),
            "CFD" => Ok(Currency::CFD),
            "BAT" => Ok(Currency::BAT),
            "CJ" => Ok(Currency::CJ),
            "BCC" => Ok(Currency::BCC),
            "BCN" => Ok(Currency::BCN),
            "BCO" => Ok(Currency::BCO),
            "BCPT" => Ok(Currency::BCPT),
            "BCY" => Ok(Currency::BCY),
            "BDL" => Ok(Currency::BDL),
            "BELA" => Ok(Currency::BELA),
            "CMPCO" => Ok(Currency::CMPCO),
            "COAL" => Ok(Currency::COAL),
            "CPAY" => Ok(Currency::CPAY),
            "BIS" => Ok(Currency::BIS),
            "BITB" => Ok(Currency::BITB),
            "BITCNY" => Ok(Currency::BITCNY),
            "DAXX" => Ok(Currency::DAXX),
            "DBC" => Ok(Currency::DBC),
            "DBET" => Ok(Currency::DBET),
            "BITUSD" => Ok(Currency::BITUSD),
            "DCY" => Ok(Currency::DCY),
            "BLITZ" => Ok(Currency::BLITZ),
            "BLK" => Ok(Currency::BLK),
            "BLOCK" => Ok(Currency::BLOCK),
            "DIX" => Ok(Currency::DIX),
            "BMC" => Ok(Currency::BMC),
            "BNB" => Ok(Currency::BNB),
            "BNT" => Ok(Currency::BNT),
            "DNR" => Ok(Currency::DNR),
            "DOVU" => Ok(Currency::DOVU),
            "DP" => Ok(Currency::DP),
            "DRP" => Ok(Currency::DRP),
            "EAC" => Ok(Currency::EAC),
            "BRK" => Ok(Currency::BRK),
            "ECC" => Ok(Currency::ECC),
            "BSD" => Ok(Currency::BSD),
            "BSR" => Ok(Currency::BSR),
            "ELLA" => Ok(Currency::ELLA),
            "BTCD" => Ok(Currency::BTCD),
            "ENT" => Ok(Currency::ENT),
            "ERO" => Ok(Currency::ERO),
            "ESC" => Ok(Currency::ESC),
            "BTS" => Ok(Currency::BTS),
            "BTX" => Ok(Currency::BTX),
            "EXRN" => Ok(Currency::EXRN),
            "BURST" => Ok(Currency::BURST),
            "FAIR" => Ok(Currency::FAIR),
            "FJC" => Ok(Currency::FJC),
            "FLASH" => Ok(Currency::FLASH),
            "BYC" => Ok(Currency::BYC),
            "BTG" => Ok(Currency::BTG),
            "FLT" => Ok(Currency::FLT),
            "CAG" => Ok(Currency::CAG),
            "FST" => Ok(Currency::FST),
            "CANN" => Ok(Currency::CANN),
            "GAIN" => Ok(Currency::GAIN),
            "GBRC" => Ok(Currency::GBRC),
            "CDT" => Ok(Currency::CDT),
            "GMT" => Ok(Currency::GMT),
            "CFI" => Ok(Currency::CFI),
            "CHC" => Ok(Currency::CHC),
            "GRID" => Ok(Currency::GRID),
            "GRWI" => Ok(Currency::GRWI),
            "CLAM" => Ok(Currency::CLAM),
            "GTC" => Ok(Currency::GTC),
            "CLOAK" => Ok(Currency::CLOAK),
            "CLUB" => Ok(Currency::CLUB),
            "HBC" => Ok(Currency::HBC),
            "CND" => Ok(Currency::CND),
            "HGT" => Ok(Currency::HGT),
            "HPY" => Ok(Currency::HPY),
            "CNX" => Ok(Currency::CNX),
            "HTML" => Ok(Currency::HTML),
            "COB" => Ok(Currency::COB),
            "COLX" => Ok(Currency::COLX),
            "HTML5" => Ok(Currency::HTML5),
            "HUC" => Ok(Currency::HUC),
            "HYP" => Ok(Currency::HYP),
            "COSS" => Ok(Currency::COSS),
            "ICOS" => Ok(Currency::ICOS),
            "COVAL" => Ok(Currency::COVAL),
            "ICX" => Ok(Currency::ICX),
            "CPC" => Ok(Currency::CPC),
            "IFC" => Ok(Currency::IFC),
            "IGNIS" => Ok(Currency::IGNIS),
            "CRB" => Ok(Currency::CRB),
            "INXT" => Ok(Currency::INXT),
            "CRW" => Ok(Currency::CRW),
            "CSNO" => Ok(Currency::CSNO),
            "JINN" => Ok(Currency::JINN),
            "KARMA" => Ok(Currency::KARMA),
            "CTR" => Ok(Currency::CTR),
            "KBR" => Ok(Currency::KBR),
            "CURE" => Ok(Currency::CURE),
            "CVC" => Ok(Currency::CVC),
            "KEK" => Ok(Currency::KEK),
            "KRB" => Ok(Currency::KRB),
            "LANA" => Ok(Currency::LANA),
            "DASH" => Ok(Currency::DASH),
            "LIFE" => Ok(Currency::LIFE),
            "DATA" => Ok(Currency::DATA),
            "LINX" => Ok(Currency::LINX),
            "DBIX" => Ok(Currency::DBIX),
            "DCN" => Ok(Currency::DCN),
            "DCR" => Ok(Currency::DCR),
            "LOC" => Ok(Currency::LOC),
            "DCT" => Ok(Currency::DCT),
            "DENT" => Ok(Currency::DENT),
            "DGB" => Ok(Currency::DGB),
            "MEC" => Ok(Currency::MEC),
            "DGD" => Ok(Currency::DGD),
            "DIME" => Ok(Currency::DIME),
            "MGC" => Ok(Currency::MGC),
            "DLT" => Ok(Currency::DLT),
            "DMD" => Ok(Currency::DMD),
            "DNT" => Ok(Currency::DNT),
            "DOGE" => Ok(Currency::DOGE),
            "MOT" => Ok(Currency::MOT),
            "DOPE" => Ok(Currency::DOPE),
            "DOT" => Ok(Currency::DOT),
            "MYB" => Ok(Currency::MYB),
            "MZC" => Ok(Currency::MZC),
            "DTB" => Ok(Currency::DTB),
            "NEU" => Ok(Currency::NEU),
            "NIO" => Ok(Currency::NIO),
            "DYN" => Ok(Currency::DYN),
            "NOBL" => Ok(Currency::NOBL),
            "EBST" => Ok(Currency::EBST),
            "NYC" => Ok(Currency::NYC),
            "EDG" => Ok(Currency::EDG),
            "EDO" => Ok(Currency::EDO),
            "EDR" => Ok(Currency::EDR),
            "EFL" => Ok(Currency::EFL),
            "OPT" => Ok(Currency::OPT),
            "EGC" => Ok(Currency::EGC),
            "PAYP" => Ok(Currency::PAYP),
            "ELIX" => Ok(Currency::ELIX),
            "PIGGY" => Ok(Currency::PIGGY),
            "PING" => Ok(Currency::PING),
            "EMC" => Ok(Currency::EMC),
            "EMC2" => Ok(Currency::EMC2),
            "PIX" => Ok(Currency::PIX),
            "PKT" => Ok(Currency::PKT),
            "ENG" => Ok(Currency::ENG),
            "ENJ" => Ok(Currency::ENJ),
            "ENRG" => Ok(Currency::ENRG),
            "PLAY" => Ok(Currency::PLAY),
            "PND" => Ok(Currency::PND),
            "EOS" => Ok(Currency::EOS),
            "ERC" => Ok(Currency::ERC),
            "ESP" => Ok(Currency::ESP),
            "PRE" => Ok(Currency::PRE),
            "ETHD" => Ok(Currency::ETHD),
            "ETN" => Ok(Currency::ETN),
            "ETP" => Ok(Currency::ETP),
            "PRIX" => Ok(Currency::PRIX),
            "QAU" => Ok(Currency::QAU),
            "EVX" => Ok(Currency::EVX),
            "EXCL" => Ok(Currency::EXCL),
            "QLC" => Ok(Currency::QLC),
            "QRK" => Ok(Currency::QRK),
            "EXP" => Ok(Currency::EXP),
            "QVT" => Ok(Currency::QVT),
            "RAIN" => Ok(Currency::RAIN),
            "RBT" => Ok(Currency::RBT),
            "FCT" => Ok(Currency::FCT),
            "RKC" => Ok(Currency::RKC),
            "FLDC" => Ok(Currency::FLDC),
            "RMC" => Ok(Currency::RMC),
            "FLO" => Ok(Currency::FLO),
            "RUP" => Ok(Currency::RUP),
            "SAFEX" => Ok(Currency::SAFEX),
            "FRGC" => Ok(Currency::FRGC),
            "SCL" => Ok(Currency::SCL),
            "SEND" => Ok(Currency::SEND),
            "FRST" => Ok(Currency::FRST),
            "SHND" => Ok(Currency::SHND),
            "FTC" => Ok(Currency::FTC),
            "FUEL" => Ok(Currency::FUEL),
            "FUN" => Ok(Currency::FUN),
            "GAM" => Ok(Currency::GAM),
            "GAME" => Ok(Currency::GAME),
            "SPRTS" => Ok(Currency::SPRTS),
            "GAS" => Ok(Currency::GAS),
            "SSS" => Ok(Currency::SSS),
            "ST" => Ok(Currency::ST),
            "STAK" => Ok(Currency::STAK),
            "GBG" => Ok(Currency::GBG),
            "STAR" => Ok(Currency::STAR),
            "GBYTE" => Ok(Currency::GBYTE),
            "GCR" => Ok(Currency::GCR),
            "GEO" => Ok(Currency::GEO),
            "GLD" => Ok(Currency::GLD),
            "TFL" => Ok(Currency::TFL),
            "GNO" => Ok(Currency::GNO),
            "GNT" => Ok(Currency::GNT),
            "TIPS" => Ok(Currency::TIPS),
            "GOLOS" => Ok(Currency::GOLOS),
            "GRC" => Ok(Currency::GRC),
            "TOK" => Ok(Currency::TOK),
            "TRC" => Ok(Currency::TRC),
            "GRS" => Ok(Currency::GRS),
            "TRUMP" => Ok(Currency::TRUMP),
            "TRUST" => Ok(Currency::TRUST),
            "TTC" => Ok(Currency::TTC),
            "GUP" => Ok(Currency::GUP),
            "GXS" => Ok(Currency::GXS),
            "UFR" => Ok(Currency::UFR),
            "UIS" => Ok(Currency::UIS),
            "UNIFY" => Ok(Currency::UNIFY),
            "HDG" => Ok(Currency::HDG),
            "UTK" => Ok(Currency::UTK),
            "VASH" => Ok(Currency::VASH),
            "VEN" => Ok(Currency::VEN),
            "HMQ" => Ok(Currency::HMQ),
            "VIVO" => Ok(Currency::VIVO),
            "HSR" => Ok(Currency::HSR),
            "HUSH" => Ok(Currency::HUSH),
            "VRS" => Ok(Currency::VRS),
            "HVN" => Ok(Currency::HVN),
            "VSX" => Ok(Currency::VSX),
            "WDC" => Ok(Currency::WDC),
            "WILD" => Ok(Currency::WILD),
            "IFT" => Ok(Currency::IFT),
            "XCN" => Ok(Currency::XCN),
            "INCNT" => Ok(Currency::INCNT),
            "IND" => Ok(Currency::IND),
            "XCS" => Ok(Currency::XCS),
            "INF" => Ok(Currency::INF),
            "INFX" => Ok(Currency::INFX),
            "XFT" => Ok(Currency::XFT),
            "XGOX" => Ok(Currency::XGOX),
            "IOC" => Ok(Currency::IOC),
            "ION" => Ok(Currency::ION),
            "IOP" => Ok(Currency::IOP),
            "XLC" => Ok(Currency::XLC),
            "XPD" => Ok(Currency::XPD),
            "IXT" => Ok(Currency::IXT),
            "KCS" => Ok(Currency::KCS),
            "ZCG" => Ok(Currency::ZCG),
            "ZENGOLD" => Ok(Currency::ZENGOLD),
            "KICK" => Ok(Currency::KICK),
            "KIN" => Ok(Currency::KIN),
            "KLN" => Ok(Currency::KLN),
            "KMD" => Ok(Currency::KMD),
            "KORE" => Ok(Currency::KORE),
            "LA" => Ok(Currency::LA),
            "LBC" => Ok(Currency::LBC),
            "LGD" => Ok(Currency::LGD),
            "LINDA" => Ok(Currency::LINDA),
            "LINK" => Ok(Currency::LINK),
            "LKK" => Ok(Currency::LKK),
            "LLT" => Ok(Currency::LLT),
            "LMC" => Ok(Currency::LMC),
            "ICN" => Ok(Currency::ICN),
            "LRC" => Ok(Currency::LRC),
            "LSK" => Ok(Currency::LSK),
            "LUN" => Ok(Currency::LUN),
            "LUX" => Ok(Currency::LUX),
            "MAID" => Ok(Currency::MAID),
            "MANA" => Ok(Currency::MANA),
            "MCAP" => Ok(Currency::MCAP),
            "MCO" => Ok(Currency::MCO),
            "MDA" => Ok(Currency::MDA),
            "MEME" => Ok(Currency::MEME),
            "MER" => Ok(Currency::MER),
            "MGO" => Ok(Currency::MGO),
            "MINT" => Ok(Currency::MINT),
            "MIOTA" => Ok(Currency::MIOTA),
            "MLN" => Ok(Currency::MLN),
            "MNX" => Ok(Currency::MNX),
            "MOD" => Ok(Currency::MOD),
            "MOIN" => Ok(Currency::MOIN),
            "MONA" => Ok(Currency::MONA),
            "MOON" => Ok(Currency::MOON),
            "KNC" => Ok(Currency::KNC),
            "MRT" => Ok(Currency::MRT),
            "MSP" => Ok(Currency::MSP),
            "MTH" => Ok(Currency::MTH),
            "MTL" => Ok(Currency::MTL),
            "MUE" => Ok(Currency::MUE),
            "MUSIC" => Ok(Currency::MUSIC),
            "MYST" => Ok(Currency::MYST),
            "NAS" => Ok(Currency::NAS),
            "NAV" => Ok(Currency::NAV),
            "NEBL" => Ok(Currency::NEBL),
            "NEO" => Ok(Currency::NEO),
            "NEOS" => Ok(Currency::NEOS),
            "NLC2" => Ok(Currency::NLC2),
            "NLG" => Ok(Currency::NLG),
            "NMC" => Ok(Currency::NMC),
            "NMR" => Ok(Currency::NMR),
            "NULS" => Ok(Currency::NULS),
            "NVC" => Ok(Currency::NVC),
            "NXC" => Ok(Currency::NXC),
            "NXS" => Ok(Currency::NXS),
            "NXT" => Ok(Currency::NXT),
            "OAX" => Ok(Currency::OAX),
            "OCT" => Ok(Currency::OCT),
            "ODN" => Ok(Currency::ODN),
            "OK" => Ok(Currency::OK),
            "OMG" => Ok(Currency::OMG),
            "OMNI" => Ok(Currency::OMNI),
            "ONION" => Ok(Currency::ONION),
            "ORME" => Ok(Currency::ORME),
            "OTN" => Ok(Currency::OTN),
            "PAC" => Ok(Currency::PAC),
            "PART" => Ok(Currency::PART),
            "PASC" => Ok(Currency::PASC),
            "PAY" => Ok(Currency::PAY),
            "PDC" => Ok(Currency::PDC),
            "PEPECASH" => Ok(Currency::PEPECASH),
            "PINK" => Ok(Currency::PINK),
            "PIRL" => Ok(Currency::PIRL),
            "PIVX" => Ok(Currency::PIVX),
            "PKB" => Ok(Currency::PKB),
            "PLBT" => Ok(Currency::PLBT),
            "PLR" => Ok(Currency::PLR),
            "POE" => Ok(Currency::POE),
            "POLL" => Ok(Currency::POLL),
            "POSW" => Ok(Currency::POSW),
            "POT" => Ok(Currency::POT),
            "POWR" => Ok(Currency::POWR),
            "PPC" => Ok(Currency::PPC),
            "PPP" => Ok(Currency::PPP),
            "PPT" => Ok(Currency::PPT),
            "NET" => Ok(Currency::NET),
            "PRG" => Ok(Currency::PRG),
            "PST" => Ok(Currency::PST),
            "PTC" => Ok(Currency::PTC),
            "PTOY" => Ok(Currency::PTOY),
            "PURA" => Ok(Currency::PURA),
            "QRL" => Ok(Currency::QRL),
            "QTUM" => Ok(Currency::QTUM),
            "QWARK" => Ok(Currency::QWARK),
            "R" => Ok(Currency::R),
            "RADS" => Ok(Currency::RADS),
            "RBY" => Ok(Currency::RBY),
            "RDD" => Ok(Currency::RDD),
            "REC" => Ok(Currency::REC),
            "REP" => Ok(Currency::REP),
            "REQ" => Ok(Currency::REQ),
            "RHOC" => Ok(Currency::RHOC),
            "RIC" => Ok(Currency::RIC),
            "RISE" => Ok(Currency::RISE),
            "RLC" => Ok(Currency::RLC),
            "RPX" => Ok(Currency::RPX),
            "RVT" => Ok(Currency::RVT),
            "SALT" => Ok(Currency::SALT),
            "SAN" => Ok(Currency::SAN),
            "SBD" => Ok(Currency::SBD),
            "SC" => Ok(Currency::SC),
            "SEQ" => Ok(Currency::SEQ),
            "SHIFT" => Ok(Currency::SHIFT),
            "SIB" => Ok(Currency::SIB),
            "SKY" => Ok(Currency::SKY),
            "SLR" => Ok(Currency::SLR),
            "SLS" => Ok(Currency::SLS),
            "SNC" => Ok(Currency::SNC),
            "SNGLS" => Ok(Currency::SNGLS),
            "SNM" => Ok(Currency::SNM),
            "SNRG" => Ok(Currency::SNRG),
            "SNT" => Ok(Currency::SNT),
            "SPHR" => Ok(Currency::SPHR),
            "QBT" => Ok(Currency::QBT),
            "SPR" => Ok(Currency::SPR),
            "START" => Ok(Currency::START),
            "STEEM" => Ok(Currency::STEEM),
            "STORJ" => Ok(Currency::STORJ),
            "STRAT" => Ok(Currency::STRAT),
            "STX" => Ok(Currency::STX),
            "SUB" => Ok(Currency::SUB),
            "SUMO" => Ok(Currency::SUMO),
            "RCN" => Ok(Currency::RCN),
            "SWIFT" => Ok(Currency::SWIFT),
            "SWT" => Ok(Currency::SWT),
            "SXC" => Ok(Currency::SXC),
            "SYNX" => Ok(Currency::SYNX),
            "SYS" => Ok(Currency::SYS),
            "TAAS" => Ok(Currency::TAAS),
            "THC" => Ok(Currency::THC),
            "TIME" => Ok(Currency::TIME),
            "TKN" => Ok(Currency::TKN),
            "TKS" => Ok(Currency::TKS),
            "TNT" => Ok(Currency::TNT),
            "TRIG" => Ok(Currency::TRIG),
            "TRST" => Ok(Currency::TRST),
            "TRX" => Ok(Currency::TRX),
            "TX" => Ok(Currency::TX),
            "UBQ" => Ok(Currency::UBQ),
            "UGT" => Ok(Currency::UGT),
            "UNB" => Ok(Currency::UNB),
            "SMART" => Ok(Currency::SMART),
            "USDT" => Ok(Currency::USDT),
            "USNBT" => Ok(Currency::USNBT),
            "VERI" => Ok(Currency::VERI),
            "VIA" => Ok(Currency::VIA),
            "VIB" => Ok(Currency::VIB),
            "VIBE" => Ok(Currency::VIBE),
            "VOISE" => Ok(Currency::VOISE),
            "VOX" => Ok(Currency::VOX),
            "VRC" => Ok(Currency::VRC),
            "VRM" => Ok(Currency::VRM),
            "VTC" => Ok(Currency::VTC),
            "VTR" => Ok(Currency::VTR),
            "WAVES" => Ok(Currency::WAVES),
            "WCT" => Ok(Currency::WCT),
            "WGR" => Ok(Currency::WGR),
            "WINGS" => Ok(Currency::WINGS),
            "WTC" => Ok(Currency::WTC),
            "XAS" => Ok(Currency::XAS),
            "XAUR" => Ok(Currency::XAUR),
            "XBC" => Ok(Currency::XBC),
            "XBY" => Ok(Currency::XBY),
            "XCP" => Ok(Currency::XCP),
            "XDN" => Ok(Currency::XDN),
            "XEL" => Ok(Currency::XEL),
            "XEM" => Ok(Currency::XEM),
            "XIN" => Ok(Currency::XIN),
            "XLM" => Ok(Currency::XLM),
            "XLR" => Ok(Currency::XLR),
            "XMCC" => Ok(Currency::XMCC),
            "XMG" => Ok(Currency::XMG),
            "XMR" => Ok(Currency::XMR),
            "XMY" => Ok(Currency::XMY),
            "XP" => Ok(Currency::XP),
            "XPM" => Ok(Currency::XPM),
            "XRB" => Ok(Currency::XRB),
            "XRL" => Ok(Currency::XRL),
            "XSH" => Ok(Currency::XSH),
            "XSPEC" => Ok(Currency::XSPEC),
            "XST" => Ok(Currency::XST),
            "XTZ" => Ok(Currency::XTZ),
            "XUC" => Ok(Currency::XUC),
            "XVC" => Ok(Currency::XVC),
            "XVG" => Ok(Currency::XVG),
            "XWC" => Ok(Currency::XWC),
            "XZC" => Ok(Currency::XZC),
            "YOYOW" => Ok(Currency::YOYOW),
            "ZCL" => Ok(Currency::ZCL),
            "ZEN" => Ok(Currency::ZEN),
            "ZER" => Ok(Currency::ZER),
            "ZNY" => Ok(Currency::ZNY),
            "ZOI" => Ok(Currency::ZOI),
            "ZRX" => Ok(Currency::ZRX),
            "ZSC" => Ok(Currency::ZSC),
            "ELTCOIN" => Ok(Currency::ELTCOIN),
            "UKG" => Ok(Currency::UKG),
            "AI" => Ok(Currency::AI),
            "ALQO" => Ok(Currency::ALQO),
            "AMM" => Ok(Currency::AMM),
            "ARN" => Ok(Currency::ARN),
            "BCD" => Ok(Currency::BCD),
            "BCX" => Ok(Currency::BCX),
            "BIX" => Ok(Currency::BIX),
            "BNTY" => Ok(Currency::BNTY),
            "BOT" => Ok(Currency::BOT),
            "BRD" => Ok(Currency::BRD),
            "BTCA" => Ok(Currency::BTCA),
            "BTE" => Ok(Currency::BTE),
            "BWK" => Ok(Currency::BWK),
            "CAPP" => Ok(Currency::CAPP),
            "CRC" => Ok(Currency::CRC),
            "CRED" => Ok(Currency::CRED),
            "DAI" => Ok(Currency::DAI),
            "DAT" => Ok(Currency::DAT),
            "DEW" => Ok(Currency::DEW),
            "DIM" => Ok(Currency::DIM),
            "DIVX" => Ok(Currency::DIVX),
            "DNA" => Ok(Currency::DNA),
            "DPY" => Ok(Currency::DPY),
            "DRGN" => Ok(Currency::DRGN),
            "DTR" => Ok(Currency::DTR),
            "EAG" => Ok(Currency::EAG),
            "ELF" => Ok(Currency::ELF),
            "ETHOS" => Ok(Currency::ETHOS),
            "FIL" => Ok(Currency::FIL),
            "FLIXX" => Ok(Currency::FLIXX),
            "GBX" => Ok(Currency::GBX),
            "GNX" => Ok(Currency::GNX),
            "GRX" => Ok(Currency::GRX),
            "GTO" => Ok(Currency::GTO),
            "GVT" => Ok(Currency::GVT),
            "HAT" => Ok(Currency::HAT),
            "HST" => Ok(Currency::HST),
            "HWC" => Ok(Currency::HWC),
            "INK" => Ok(Currency::INK),
            "INN" => Ok(Currency::INN),
            "ITC" => Ok(Currency::ITC),
            "ITNS" => Ok(Currency::ITNS),
            "LEND" => Ok(Currency::LEND),
            "MAG" => Ok(Currency::MAG),
            "MAGE" => Ok(Currency::MAGE),
            "MDS" => Ok(Currency::MDS),
            "MED" => Ok(Currency::MED),
            "MKR" => Ok(Currency::MKR),
            "NGC" => Ok(Currency::NGC),
            "PBL" => Ok(Currency::PBL),
            "PFR" => Ok(Currency::PFR),
            "PHR" => Ok(Currency::PHR),
            "PRL" => Ok(Currency::PRL),
            "QASH" => Ok(Currency::QASH),
            "QSP" => Ok(Currency::QSP),
            "RDN" => Ok(Currency::RDN),
            "SAGA" => Ok(Currency::SAGA),
            "SBTC" => Ok(Currency::SBTC),
            "SMT" => Ok(Currency::SMT),
            "SNOV" => Ok(Currency::SNOV),
            "SPANK" => Ok(Currency::SPANK),
            "SPF" => Ok(Currency::SPF),
            "SPHTX" => Ok(Currency::SPHTX),
            "SRN" => Ok(Currency::SRN),
            "STORM" => Ok(Currency::STORM),
            "TIX" => Ok(Currency::TIX),
            "TNB" => Ok(Currency::TNB),
            "TSL" => Ok(Currency::TSL),
            "XID" => Ok(Currency::XID),
            "UBTC" => Ok(Currency::UBTC),
            "UQC" => Ok(Currency::UQC),
            "VEE" => Ok(Currency::VEE),
            "VIU" => Ok(Currency::VIU),
            "WABI" => Ok(Currency::WABI),
            "WAX" => Ok(Currency::WAX),
            "WC" => Ok(Currency::WC),
            "WISH" => Ok(Currency::WISH),
            "WRC" => Ok(Currency::WRC),
            "XCPO" => Ok(Currency::XCPO),
            _ => Err(ErrorKind::UnknownCurrency(name.to_owned()).into()),
        }
    }
}

impl ::std::fmt::Debug for Currency {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        let symbol = match self {
            &Currency::EUR => "EUR",
            &Currency::USD => "USD",
            &Currency::BTC => "BTC",
            &Currency::ETH => "ETH",
            &Currency::ETC => "ETC",
            &Currency::XRP => "XRP",
            &Currency::ZEC => "ZEC",
            &Currency::BCH => "BCH",
            &Currency::LTC => "LTC",
            &Currency::ACE => "ACE",
            &Currency::ABY => "ABY",
            &Currency::ACT => "ACT",
            &Currency::ADA => "ADA",
            &Currency::ANI => "ANI",
            &Currency::APX => "APX",
            &Currency::ADT => "ADT",
            &Currency::ADX => "ADX",
            &Currency::ATM => "ATM",
            &Currency::AE => "AE",
            &Currency::AEON => "AEON",
            &Currency::ATMS => "ATMS",
            &Currency::AGRS => "AGRS",
            &Currency::ATOM => "ATOM",
            &Currency::ATS => "ATS",
            &Currency::AION => "AION",
            &Currency::AIR => "AIR",
            &Currency::B3 => "B3",
            &Currency::ALIS => "ALIS",
            &Currency::BBT => "BBT",
            &Currency::BCDN => "BCDN",
            &Currency::AMB => "AMB",
            &Currency::AMP => "AMP",
            &Currency::ANT => "ANT",
            &Currency::BEST => "BEST",
            &Currency::BET => "BET",
            &Currency::BIG => "BIG",
            &Currency::ARDR => "ARDR",
            &Currency::BLUE => "BLUE",
            &Currency::ARK => "ARK",
            &Currency::BNX => "BNX",
            &Currency::AST => "AST",
            &Currency::ATB => "ATB",
            &Currency::BRX => "BRX",
            &Currency::ATMC => "ATMC",
            &Currency::BTCZ => "BTCZ",
            &Currency::AUR => "AUR",
            &Currency::AVT => "AVT",
            &Currency::BUZZ => "BUZZ",
            &Currency::B2X => "B2X",
            &Currency::BAY => "BAY",
            &Currency::CFD => "CFD",
            &Currency::BAT => "BAT",
            &Currency::CJ => "CJ",
            &Currency::BCC => "BCC",
            &Currency::BCN => "BCN",
            &Currency::BCO => "BCO",
            &Currency::BCPT => "BCPT",
            &Currency::BCY => "BCY",
            &Currency::BDL => "BDL",
            &Currency::BELA => "BELA",
            &Currency::CMPCO => "CMPCO",
            &Currency::COAL => "COAL",
            &Currency::CPAY => "CPAY",
            &Currency::BIS => "BIS",
            &Currency::BITB => "BITB",
            &Currency::BITCNY => "BITCNY",
            &Currency::DAXX => "DAXX",
            &Currency::DBC => "DBC",
            &Currency::DBET => "DBET",
            &Currency::BITUSD => "BITUSD",
            &Currency::DCY => "DCY",
            &Currency::BLITZ => "BLITZ",
            &Currency::BLK => "BLK",
            &Currency::BLOCK => "BLOCK",
            &Currency::DIX => "DIX",
            &Currency::BMC => "BMC",
            &Currency::BNB => "BNB",
            &Currency::BNT => "BNT",
            &Currency::DNR => "DNR",
            &Currency::DOVU => "DOVU",
            &Currency::DP => "DP",
            &Currency::DRP => "DRP",
            &Currency::EAC => "EAC",
            &Currency::BRK => "BRK",
            &Currency::ECC => "ECC",
            &Currency::BSD => "BSD",
            &Currency::BSR => "BSR",
            &Currency::ELLA => "ELLA",
            &Currency::BTCD => "BTCD",
            &Currency::ENT => "ENT",
            &Currency::ERO => "ERO",
            &Currency::ESC => "ESC",
            &Currency::BTS => "BTS",
            &Currency::BTX => "BTX",
            &Currency::EXRN => "EXRN",
            &Currency::BURST => "BURST",
            &Currency::FAIR => "FAIR",
            &Currency::FJC => "FJC",
            &Currency::FLASH => "FLASH",
            &Currency::BYC => "BYC",
            &Currency::BTG => "BTG",
            &Currency::FLT => "FLT",
            &Currency::CAG => "CAG",
            &Currency::FST => "FST",
            &Currency::CANN => "CANN",
            &Currency::GAIN => "GAIN",
            &Currency::GBRC => "GBRC",
            &Currency::CDT => "CDT",
            &Currency::GMT => "GMT",
            &Currency::CFI => "CFI",
            &Currency::CHC => "CHC",
            &Currency::GRID => "GRID",
            &Currency::GRWI => "GRWI",
            &Currency::CLAM => "CLAM",
            &Currency::GTC => "GTC",
            &Currency::CLOAK => "CLOAK",
            &Currency::CLUB => "CLUB",
            &Currency::HBC => "HBC",
            &Currency::CND => "CND",
            &Currency::HGT => "HGT",
            &Currency::HPY => "HPY",
            &Currency::CNX => "CNX",
            &Currency::HTML => "HTML",
            &Currency::COB => "COB",
            &Currency::COLX => "COLX",
            &Currency::HTML5 => "HTML5",
            &Currency::HUC => "HUC",
            &Currency::HYP => "HYP",
            &Currency::COSS => "COSS",
            &Currency::ICOS => "ICOS",
            &Currency::COVAL => "COVAL",
            &Currency::ICX => "ICX",
            &Currency::CPC => "CPC",
            &Currency::IFC => "IFC",
            &Currency::IGNIS => "IGNIS",
            &Currency::CRB => "CRB",
            &Currency::INXT => "INXT",
            &Currency::CRW => "CRW",
            &Currency::CSNO => "CSNO",
            &Currency::JINN => "JINN",
            &Currency::KARMA => "KARMA",
            &Currency::CTR => "CTR",
            &Currency::KBR => "KBR",
            &Currency::CURE => "CURE",
            &Currency::CVC => "CVC",
            &Currency::KEK => "KEK",
            &Currency::KRB => "KRB",
            &Currency::LANA => "LANA",
            &Currency::DASH => "DASH",
            &Currency::LIFE => "LIFE",
            &Currency::DATA => "DATA",
            &Currency::LINX => "LINX",
            &Currency::DBIX => "DBIX",
            &Currency::DCN => "DCN",
            &Currency::DCR => "DCR",
            &Currency::LOC => "LOC",
            &Currency::DCT => "DCT",
            &Currency::DENT => "DENT",
            &Currency::DGB => "DGB",
            &Currency::MEC => "MEC",
            &Currency::DGD => "DGD",
            &Currency::DIME => "DIME",
            &Currency::MGC => "MGC",
            &Currency::DLT => "DLT",
            &Currency::DMD => "DMD",
            &Currency::DNT => "DNT",
            &Currency::DOGE => "DOGE",
            &Currency::MOT => "MOT",
            &Currency::DOPE => "DOPE",
            &Currency::DOT => "DOT",
            &Currency::MYB => "MYB",
            &Currency::MZC => "MZC",
            &Currency::DTB => "DTB",
            &Currency::NEU => "NEU",
            &Currency::NIO => "NIO",
            &Currency::DYN => "DYN",
            &Currency::NOBL => "NOBL",
            &Currency::EBST => "EBST",
            &Currency::NYC => "NYC",
            &Currency::EDG => "EDG",
            &Currency::EDO => "EDO",
            &Currency::EDR => "EDR",
            &Currency::EFL => "EFL",
            &Currency::OPT => "OPT",
            &Currency::EGC => "EGC",
            &Currency::PAYP => "PAYP",
            &Currency::ELIX => "ELIX",
            &Currency::PIGGY => "PIGGY",
            &Currency::PING => "PING",
            &Currency::EMC => "EMC",
            &Currency::EMC2 => "EMC2",
            &Currency::PIX => "PIX",
            &Currency::PKT => "PKT",
            &Currency::ENG => "ENG",
            &Currency::ENJ => "ENJ",
            &Currency::ENRG => "ENRG",
            &Currency::PLAY => "PLAY",
            &Currency::PND => "PND",
            &Currency::EOS => "EOS",
            &Currency::ERC => "ERC",
            &Currency::ESP => "ESP",
            &Currency::PRE => "PRE",
            &Currency::ETHD => "ETHD",
            &Currency::ETN => "ETN",
            &Currency::ETP => "ETP",
            &Currency::PRIX => "PRIX",
            &Currency::QAU => "QAU",
            &Currency::EVX => "EVX",
            &Currency::EXCL => "EXCL",
            &Currency::QLC => "QLC",
            &Currency::QRK => "QRK",
            &Currency::EXP => "EXP",
            &Currency::QVT => "QVT",
            &Currency::RAIN => "RAIN",
            &Currency::RBT => "RBT",
            &Currency::FCT => "FCT",
            &Currency::RKC => "RKC",
            &Currency::FLDC => "FLDC",
            &Currency::RMC => "RMC",
            &Currency::FLO => "FLO",
            &Currency::RUP => "RUP",
            &Currency::SAFEX => "SAFEX",
            &Currency::FRGC => "FRGC",
            &Currency::SCL => "SCL",
            &Currency::SEND => "SEND",
            &Currency::FRST => "FRST",
            &Currency::SHND => "SHND",
            &Currency::FTC => "FTC",
            &Currency::FUEL => "FUEL",
            &Currency::FUN => "FUN",
            &Currency::GAM => "GAM",
            &Currency::GAME => "GAME",
            &Currency::SPRTS => "SPRTS",
            &Currency::GAS => "GAS",
            &Currency::SSS => "SSS",
            &Currency::ST => "ST",
            &Currency::STAK => "STAK",
            &Currency::GBG => "GBG",
            &Currency::STAR => "STAR",
            &Currency::GBYTE => "GBYTE",
            &Currency::GCR => "GCR",
            &Currency::GEO => "GEO",
            &Currency::GLD => "GLD",
            &Currency::TFL => "TFL",
            &Currency::GNO => "GNO",
            &Currency::GNT => "GNT",
            &Currency::TIPS => "TIPS",
            &Currency::GOLOS => "GOLOS",
            &Currency::GRC => "GRC",
            &Currency::TOK => "TOK",
            &Currency::TRC => "TRC",
            &Currency::GRS => "GRS",
            &Currency::TRUMP => "TRUMP",
            &Currency::TRUST => "TRUST",
            &Currency::TTC => "TTC",
            &Currency::GUP => "GUP",
            &Currency::GXS => "GXS",
            &Currency::UFR => "UFR",
            &Currency::UIS => "UIS",
            &Currency::UNIFY => "UNIFY",
            &Currency::HDG => "HDG",
            &Currency::UTK => "UTK",
            &Currency::VASH => "VASH",
            &Currency::VEN => "VEN",
            &Currency::HMQ => "HMQ",
            &Currency::VIVO => "VIVO",
            &Currency::HSR => "HSR",
            &Currency::HUSH => "HUSH",
            &Currency::VRS => "VRS",
            &Currency::HVN => "HVN",
            &Currency::VSX => "VSX",
            &Currency::WDC => "WDC",
            &Currency::WILD => "WILD",
            &Currency::IFT => "IFT",
            &Currency::XCN => "XCN",
            &Currency::INCNT => "INCNT",
            &Currency::IND => "IND",
            &Currency::XCS => "XCS",
            &Currency::INF => "INF",
            &Currency::INFX => "INFX",
            &Currency::XFT => "XFT",
            &Currency::XGOX => "XGOX",
            &Currency::IOC => "IOC",
            &Currency::ION => "ION",
            &Currency::IOP => "IOP",
            &Currency::XLC => "XLC",
            &Currency::XPD => "XPD",
            &Currency::IXT => "IXT",
            &Currency::KCS => "KCS",
            &Currency::ZCG => "ZCG",
            &Currency::ZENGOLD => "ZENGOLD",
            &Currency::KICK => "KICK",
            &Currency::KIN => "KIN",
            &Currency::KLN => "KLN",
            &Currency::KMD => "KMD",
            &Currency::KORE => "KORE",
            &Currency::LA => "LA",
            &Currency::LBC => "LBC",
            &Currency::LGD => "LGD",
            &Currency::LINDA => "LINDA",
            &Currency::LINK => "LINK",
            &Currency::LKK => "LKK",
            &Currency::LLT => "LLT",
            &Currency::LMC => "LMC",
            &Currency::ICN => "ICN",
            &Currency::LRC => "LRC",
            &Currency::LSK => "LSK",
            &Currency::LUN => "LUN",
            &Currency::LUX => "LUX",
            &Currency::MAID => "MAID",
            &Currency::MANA => "MANA",
            &Currency::MCAP => "MCAP",
            &Currency::MCO => "MCO",
            &Currency::MDA => "MDA",
            &Currency::MEME => "MEME",
            &Currency::MER => "MER",
            &Currency::MGO => "MGO",
            &Currency::MINT => "MINT",
            &Currency::MIOTA => "MIOTA",
            &Currency::MLN => "MLN",
            &Currency::MNX => "MNX",
            &Currency::MOD => "MOD",
            &Currency::MOIN => "MOIN",
            &Currency::MONA => "MONA",
            &Currency::MOON => "MOON",
            &Currency::KNC => "KNC",
            &Currency::MRT => "MRT",
            &Currency::MSP => "MSP",
            &Currency::MTH => "MTH",
            &Currency::MTL => "MTL",
            &Currency::MUE => "MUE",
            &Currency::MUSIC => "MUSIC",
            &Currency::MYST => "MYST",
            &Currency::NAS => "NAS",
            &Currency::NAV => "NAV",
            &Currency::NEBL => "NEBL",
            &Currency::NEO => "NEO",
            &Currency::NEOS => "NEOS",
            &Currency::NLC2 => "NLC2",
            &Currency::NLG => "NLG",
            &Currency::NMC => "NMC",
            &Currency::NMR => "NMR",
            &Currency::NULS => "NULS",
            &Currency::NVC => "NVC",
            &Currency::NXC => "NXC",
            &Currency::NXS => "NXS",
            &Currency::NXT => "NXT",
            &Currency::OAX => "OAX",
            &Currency::OCT => "OCT",
            &Currency::ODN => "ODN",
            &Currency::OK => "OK",
            &Currency::OMG => "OMG",
            &Currency::OMNI => "OMNI",
            &Currency::ONION => "ONION",
            &Currency::ORME => "ORME",
            &Currency::OTN => "OTN",
            &Currency::PAC => "PAC",
            &Currency::PART => "PART",
            &Currency::PASC => "PASC",
            &Currency::PAY => "PAY",
            &Currency::PDC => "PDC",
            &Currency::PEPECASH => "PEPECASH",
            &Currency::PINK => "PINK",
            &Currency::PIRL => "PIRL",
            &Currency::PIVX => "PIVX",
            &Currency::PKB => "PKB",
            &Currency::PLBT => "PLBT",
            &Currency::PLR => "PLR",
            &Currency::POE => "POE",
            &Currency::POLL => "POLL",
            &Currency::POSW => "POSW",
            &Currency::POT => "POT",
            &Currency::POWR => "POWR",
            &Currency::PPC => "PPC",
            &Currency::PPP => "PPP",
            &Currency::PPT => "PPT",
            &Currency::NET => "NET",
            &Currency::PRG => "PRG",
            &Currency::PST => "PST",
            &Currency::PTC => "PTC",
            &Currency::PTOY => "PTOY",
            &Currency::PURA => "PURA",
            &Currency::QRL => "QRL",
            &Currency::QTUM => "QTUM",
            &Currency::QWARK => "QWARK",
            &Currency::R => "R",
            &Currency::RADS => "RADS",
            &Currency::RBY => "RBY",
            &Currency::RDD => "RDD",
            &Currency::REC => "REC",
            &Currency::REP => "REP",
            &Currency::REQ => "REQ",
            &Currency::RHOC => "RHOC",
            &Currency::RIC => "RIC",
            &Currency::RISE => "RISE",
            &Currency::RLC => "RLC",
            &Currency::RPX => "RPX",
            &Currency::RVT => "RVT",
            &Currency::SALT => "SALT",
            &Currency::SAN => "SAN",
            &Currency::SBD => "SBD",
            &Currency::SC => "SC",
            &Currency::SEQ => "SEQ",
            &Currency::SHIFT => "SHIFT",
            &Currency::SIB => "SIB",
            &Currency::SKY => "SKY",
            &Currency::SLR => "SLR",
            &Currency::SLS => "SLS",
            &Currency::SNC => "SNC",
            &Currency::SNGLS => "SNGLS",
            &Currency::SNM => "SNM",
            &Currency::SNRG => "SNRG",
            &Currency::SNT => "SNT",
            &Currency::SPHR => "SPHR",
            &Currency::QBT => "QBT",
            &Currency::SPR => "SPR",
            &Currency::START => "START",
            &Currency::STEEM => "STEEM",
            &Currency::STORJ => "STORJ",
            &Currency::STRAT => "STRAT",
            &Currency::STX => "STX",
            &Currency::SUB => "SUB",
            &Currency::SUMO => "SUMO",
            &Currency::RCN => "RCN",
            &Currency::SWIFT => "SWIFT",
            &Currency::SWT => "SWT",
            &Currency::SXC => "SXC",
            &Currency::SYNX => "SYNX",
            &Currency::SYS => "SYS",
            &Currency::TAAS => "TAAS",
            &Currency::THC => "THC",
            &Currency::TIME => "TIME",
            &Currency::TKN => "TKN",
            &Currency::TKS => "TKS",
            &Currency::TNT => "TNT",
            &Currency::TRIG => "TRIG",
            &Currency::TRST => "TRST",
            &Currency::TRX => "TRX",
            &Currency::TX => "TX",
            &Currency::UBQ => "UBQ",
            &Currency::UGT => "UGT",
            &Currency::UNB => "UNB",
            &Currency::SMART => "SMART",
            &Currency::USDT => "USDT",
            &Currency::USNBT => "USNBT",
            &Currency::VERI => "VERI",
            &Currency::VIA => "VIA",
            &Currency::VIB => "VIB",
            &Currency::VIBE => "VIBE",
            &Currency::VOISE => "VOISE",
            &Currency::VOX => "VOX",
            &Currency::VRC => "VRC",
            &Currency::VRM => "VRM",
            &Currency::VTC => "VTC",
            &Currency::VTR => "VTR",
            &Currency::WAVES => "WAVES",
            &Currency::WCT => "WCT",
            &Currency::WGR => "WGR",
            &Currency::WINGS => "WINGS",
            &Currency::WTC => "WTC",
            &Currency::XAS => "XAS",
            &Currency::XAUR => "XAUR",
            &Currency::XBC => "XBC",
            &Currency::XBY => "XBY",
            &Currency::XCP => "XCP",
            &Currency::XDN => "XDN",
            &Currency::XEL => "XEL",
            &Currency::XEM => "XEM",
            &Currency::XIN => "XIN",
            &Currency::XLM => "XLM",
            &Currency::XLR => "XLR",
            &Currency::XMCC => "XMCC",
            &Currency::XMG => "XMG",
            &Currency::XMR => "XMR",
            &Currency::XMY => "XMY",
            &Currency::XP => "XP",
            &Currency::XPM => "XPM",
            &Currency::XRB => "XRB",
            &Currency::XRL => "XRL",
            &Currency::XSH => "XSH",
            &Currency::XSPEC => "XSPEC",
            &Currency::XST => "XST",
            &Currency::XTZ => "XTZ",
            &Currency::XUC => "XUC",
            &Currency::XVC => "XVC",
            &Currency::XVG => "XVG",
            &Currency::XWC => "XWC",
            &Currency::XZC => "XZC",
            &Currency::YOYOW => "YOYOW",
            &Currency::ZCL => "ZCL",
            &Currency::ZEN => "ZEN",
            &Currency::ZER => "ZER",
            &Currency::ZNY => "ZNY",
            &Currency::ZOI => "ZOI",
            &Currency::ZRX => "ZRX",
            &Currency::ZSC => "ZSC",
            &Currency::ELTCOIN => "ELTCOIN",
            &Currency::UKG => "UKG",
            &Currency::AI => "AI",
            &Currency::ALQO => "ALQO",
            &Currency::AMM => "AMM",
            &Currency::ARN => "ARN",
            &Currency::BCD => "BCD",
            &Currency::BCX => "BCX",
            &Currency::BIX => "BIX",
            &Currency::BNTY => "BNTY",
            &Currency::BOT => "BOT",
            &Currency::BRD => "BRD",
            &Currency::BTCA => "BTCA",
            &Currency::BTE => "BTE",
            &Currency::BWK => "BWK",
            &Currency::CAPP => "CAPP",
            &Currency::CRC => "CRC",
            &Currency::CRED => "CRED",
            &Currency::DAI => "DAI",
            &Currency::DAT => "DAT",
            &Currency::DEW => "DEW",
            &Currency::DIM => "DIM",
            &Currency::DIVX => "DIVX",
            &Currency::DNA => "DNA",
            &Currency::DPY => "DPY",
            &Currency::DRGN => "DRGN",
            &Currency::DTR => "DTR",
            &Currency::EAG => "EAG",
            &Currency::ELF => "ELF",
            &Currency::ETHOS => "ETHOS",
            &Currency::FIL => "FIL",
            &Currency::FLIXX => "FLIXX",
            &Currency::GBX => "GBX",
            &Currency::GNX => "GNX",
            &Currency::GRX => "GRX",
            &Currency::GTO => "GTO",
            &Currency::GVT => "GVT",
            &Currency::HAT => "HAT",
            &Currency::HST => "HST",
            &Currency::HWC => "HWC",
            &Currency::INK => "INK",
            &Currency::INN => "INN",
            &Currency::ITC => "ITC",
            &Currency::ITNS => "ITNS",
            &Currency::LEND => "LEND",
            &Currency::MAG => "MAG",
            &Currency::MAGE => "MAGE",
            &Currency::MDS => "MDS",
            &Currency::MED => "MED",
            &Currency::MKR => "MKR",
            &Currency::NGC => "NGC",
            &Currency::PBL => "PBL",
            &Currency::PFR => "PFR",
            &Currency::PHR => "PHR",
            &Currency::PRL => "PRL",
            &Currency::QASH => "QASH",
            &Currency::QSP => "QSP",
            &Currency::RDN => "RDN",
            &Currency::SAGA => "SAGA",
            &Currency::SBTC => "SBTC",
            &Currency::SMT => "SMT",
            &Currency::SNOV => "SNOV",
            &Currency::SPANK => "SPANK",
            &Currency::SPF => "SPF",
            &Currency::SPHTX => "SPHTX",
            &Currency::SRN => "SRN",
            &Currency::STORM => "STORM",
            &Currency::TIX => "TIX",
            &Currency::TNB => "TNB",
            &Currency::TSL => "TSL",
            &Currency::XID => "XID",
            &Currency::UBTC => "UBTC",
            &Currency::UQC => "UQC",
            &Currency::VEE => "VEE",
            &Currency::VIU => "VIU",
            &Currency::WABI => "WABI",
            &Currency::WAX => "WAX",
            &Currency::WC => "WC",
            &Currency::WISH => "WISH",
            &Currency::WRC => "WRC",
            &Currency::XCPO => "XCPO",
        };
        f.write_str(symbol)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn symbol_debug() {
        let c = Currency::try_from("BTC").unwrap();
        assert_eq!("BTC".to_owned(), format!("{:?}", c));
    }
}
